import { OwnerRecord } from "@/types/dataOwner";
import { RopaStatus, DataType, CollectionMethod, RetentionUnit } from "@/types/enums";

export const mockOwnerRecords: OwnerRecord[] = [
    {
        id: "RP-2026-03",
        documentName: "ข้อมูลลูกค้าเพื่อการตลาด",
        status: RopaStatus.Processing,
        workflow: "processing",
        processorCompany: "บริษัท NetBay Marketing",
        dueDate: "20/03/2569",
        dateCreated: "01/03/2569",
        updatedDate: "10/03/2569",
        processingStatus: { doStatus: "pending", dpStatus: "pending" },
        assignedProcessor: {
            name: "นายกิตติพงศ์ สุวรรณชัย",
            assignedDate: "05/03/2569",
            processorStatus: "ไม่เสร็จสมบูรณ์",
            documentTitle: "ข้อมูลลูกค้าเพื่อการตลาด"
        },
        title: "นาย", firstName: "ธนากร", lastName: "วัฒนศิริ",
        address: "99/1 ถนนวิภาวดีรังสิต แขวงลาดยาว เขตจตุจักร กรุงเทพฯ 10900",
        email: "thanakorn.w@netbay.co.th", phoneNumber: "081-234-5678",
        rightsEmail: "dpo@netbay.co.th", rightsPhone: "02-123-4567",
        dataSubjectName: "ลูกค้าทั่วไป", processingActivity: "การส่งข่าวสารประชาสัมพันธ์", 
        purpose: "เพื่อแจ้งสิทธิประโยชน์และกิจกรรมทางการตลาด", personalData: "ชื่อ, อีเมล, เบอร์โทรศัพท์",
        dataCategories: ["customer"], dataType: DataType.General, storedDataTypes: ["ชื่อ - นามสกุล", "อีเมล", "เบอร์โทรศัพท์"],
        collectionMethod: CollectionMethod.SoftFile, 
        dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานความยินยอม (Consent)", 
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { 
            storageType: CollectionMethod.SoftFile, 
            method: ["Cloud Storage (AWS)"], 
            duration: 5, 
            unit: RetentionUnit.Year, 
            accessControl: "ฝ่ายการตลาดและฝ่าย IT", 
            deletionMethod: "ลบไฟล์ข้อมูลถาวรออกจากระบบ" 
        },
        exemptionDisclosure: "ไม่มีการใช้หรือเปิดเผยข้อมูลที่ได้รับยกเว้น",
        securityMeasures: {
            organizational: "กำหนดนโยบายความเป็นส่วนตัวและอบรมพนักงาน",
            technical: "การเข้ารหัสข้อมูล (Encryption) และ Firewall",
            accessControl: "ระบบยืนยันตัวตนแบบ 2 ชั้น (2FA)",
            responsibility: "ลงนามข้อตกลงรักษาความลับ (NDA) ทุกคน"
        }
    },
    {
        id: "RP-2026-02",
        documentName: "ข้อมูลธุรกรรมการซื้อขาย",
        status: RopaStatus.Processing,
        workflow: "processing",
        processorCompany: "บริษัท บัญชีดี จำกัด",
        dueDate: "18/03/2569",
        dateCreated: "01/03/2569",
        updatedDate: "12/03/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        assignedProcessor: {
            name: "นางสาวพิมพ์ชนก วัฒนากุล",
            assignedDate: "05/03/2569",
            processorStatus: "เสร็จสมบูรณ์",
            documentTitle: "ข้อมูลธุรกรรมการซื้อขาย"
        },
        title: "นางสาว", firstName: "กัญญา", lastName: "มณีรัตน์",
        address: "123 อาคารพญาไทพลาซ่า กรุงเทพฯ 10400",
        email: "kanya.m@accounting.co.th", phoneNumber: "089-876-5432",
        rightsEmail: "contact@accounting.co.th", rightsPhone: "02-987-6543",
        dataSubjectName: "คู่ค้าและซัพพลายเออร์", processingActivity: "Record-to-Report", 
        purpose: "เพื่อจัดทำบัญชีและเสียภาษีตามกฎหมาย", personalData: "ชื่อบริษัท, เลขประจำตัวผู้เสียภาษี",
        dataCategories: ["partner"], dataType: DataType.General, storedDataTypes: ["เลขประจำตัวประชาชน", "ชื่อ - นามสกุล"],
        collectionMethod: CollectionMethod.HardCopy, 
        dataSource: { direct: true, indirect: true },
        legalBasis: "ฐานการปฏิบัติตามกฎหมาย (Legal Obligation)", 
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { 
            storageType: CollectionMethod.HardCopy, 
            method: ["ตู้เก็บเอกสารนิรภัย"], 
            duration: 10, 
            unit: RetentionUnit.Year, 
            accessControl: "เจ้าหน้าที่บัญชีอาวุโส", 
            deletionMethod: "ใช้เครื่องทำลายเอกสาร (Shredder)" 
        },
        exemptionDisclosure: "การส่งข้อมูลให้กรมสรรพากร",
        securityMeasures: {
            physical: "ห้องเก็บเอกสารล็อคกุญแจ 2 ชั้น และมีกล้องวงจรปิด",
            audit: "มีบันทึกการเข้า-ออกห้องเก็บเอกสาร"
        }
    },
    {
        id: "RP-2026-01",
        documentName: "บันทึกการเข้าออกคลาวด์เซิร์ฟเวอร์",
        status: RopaStatus.Processing,
        workflow: "processing",
        processorCompany: "บริษัท IT Security Pro",
        dueDate: "15/03/2569",
        dateCreated: "01/03/2569",
        updatedDate: "14/03/2569",
        processingStatus: { doStatus: "done", dpStatus: "pending" },
        assignedProcessor: {
            name: "นายณัฐวุฒิ ศรีสวัสดิ์",
            assignedDate: "05/03/2569",
            processorStatus: "ไม่เสร็จสมบูรณ์",
            documentTitle: "บันทึกการเข้าออกคลาวด์เซิร์ฟเวอร์"
        },
        title: "นาย", firstName: "ปิติ", lastName: "สุขสวรรค์",
        address: "อาคารซอฟต์แวร์พาร์ค นนทบุรี",
        email: "piti.s@itsecurity.co.th", phoneNumber: "087-654-3210",
        rightsEmail: "support@itsecurity.co.th",
        dataSubjectName: "ผู้ดูแลระบบ (Admin)", processingActivity: "System Monitoring", 
        purpose: "เพื่อรักษาความมั่นคงปลอดภัยทางสารสนเทศ", personalData: "IP Address, Login Log",
        dataCategories: ["contact"], dataType: DataType.General, storedDataTypes: ["อื่นๆ"],
        storedDataTypesOther: "IP Address, MAC Address",
        collectionMethod: CollectionMethod.SoftFile, 
        dataSource: { direct: false, indirect: true },
        legalBasis: "ฐานประโยชน์โดยชอบธรรม (Legitimate Interest)", 
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: true, country: "Singapore", transferMethod: "Log Forwarding" },
        retention: { 
            storageType: CollectionMethod.SoftFile, 
            method: ["Central Log Management Server"], 
            duration: 90, 
            unit: RetentionUnit.Day, 
            accessControl: "IT Auditor", 
            deletionMethod: "Auto-overwrite by System" 
        },
        exemptionDisclosure: "ตรวจพบบุกรุกระบบส่งพยานหลักฐานให้ตำรวจ",
        securityMeasures: {
            technical: "IDS/IPS, Log Integrity Check",
            audit: "SIEM Dashboard for Audit Trail"
        }
    },
    {
        id: "RP-2026-04",
        documentName: "ระบบบริหารจัดการเงินเดือนพนักงาน",
        status: RopaStatus.ReviewPending,
        workflow: "sent_dpo",
        processorCompany: "บริษัท PayCheck Thailand",
        dueDate: "01/04/2569",
        dateCreated: "01/03/2569",
        updatedDate: "20/03/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        assignedProcessor: { name: "นางสาวศิริพร บุญเหลือ", assignedDate: "02/03/2569", processorStatus: "เสร็จสมบูรณ์", documentTitle: "ระบบบริหารจัดการเงินเดือนพนักงาน" },
        title: "นางสาว", firstName: "วิภา", lastName: "มหาทรัพย์",
        address: "เขตลาดพร้าว กรุงเทพฯ", email: "wipa@netbay.co.th", phoneNumber: "02-555-4444",
        dataSubjectName: "พนักงานประจำและสัญญาจ้าง", processingActivity: "Payroll Calculation", 
        purpose: "เพื่อคำนวณเงินเดือนและนำส่งภาษี/ประกันสังคม", personalData: "ชื่อ, เลขที่บัญชีธนาคาร, เงินเดือน",
        dataCategories: ["employee"], dataType: [DataType.General, DataType.Sensitive], 
        storedDataTypes: ["ชื่อ - นามสกุล", "เลขประจำตัวประชาชน", "วัน/เดือน/ปีเกิด"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานการปฏิบัติตามกฎหมาย", 
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { 
            storageType: CollectionMethod.SoftFile, 
            method: ["ERP Storage"], 
            duration: 10, 
            unit: RetentionUnit.Year, 
            accessControl: "HR Manager", 
            deletionMethod: "Purge Database Record" 
        },
        exemptionDisclosure: "นำส่งข้อมูลให้สำนักงานประกันสังคม",
        securityMeasures: { organizational: "HR Access Policy", technical: "Database Encryption" }
    },
    {
        id: "RP-2026-05",
        documentName: "ข้อมูลลูกค้าในระบบ CRM",
        status: RopaStatus.Approved,
        workflow: "approved",
        processorCompany: "บริษัท Cloud-Solution Ltd.",
        dueDate: "25/03/2569",
        dateCreated: "01/01/2569",
        updatedDate: "15/03/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        assignedProcessor: { name: "นายอรรถพล เมืองไทย", assignedDate: "05/01/2569", processorStatus: "เสร็จสมบูรณ์", documentTitle: "ข้อมูลลูกค้าในระบบ CRM" },
        title: "นาย", firstName: "สมศักดิ์", lastName: "รุ่งเรือง",
        address: "ระยอง", email: "somsak@crmpro.com", phoneNumber: "038-123-456",
        dataSubjectName: "ลูกค้าเป้าหมาย", processingActivity: "Customer Relationship Management", 
        purpose: "เพื่อวิเคราะห์พฤติกรรมการซื้อและนำเสนอโปรโมชั่น", personalData: "ประวัติการซื้อ, ความสนใจ",
        dataCategories: ["customer"], dataType: DataType.General, 
        storedDataTypes: ["ชื่อ - นามสกุล", "เบอร์โทรศัพท์", "อีเมล"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: true },
        legalBasis: "ฐานความยินยอม", 
        minorConsent: { under10: false, age10to20: true, none: false },
        internationalTransfer: { isTransfer: true, country: "USA", transferMethod: "Cloud Sync" },
        retention: { 
            storageType: CollectionMethod.SoftFile, 
            method: ["Salesforce CRM"], 
            duration: 2, 
            unit: RetentionUnit.Year, 
            accessControl: "Sales Team", 
            deletionMethod: "Delete from CRM Portal" 
        },
        exemptionDisclosure: "ไม่มี",
        securityMeasures: { organizational: "Data Privacy Policy", accessControl: "Role-based Access Control" }
    },
    {
        id: "RP-2026-06",
        documentName: "บันทึกประวัติผู้มาติดต่อ",
        status: RopaStatus.DeletePending,
        workflow: "delete_pending",
        processorCompany: "บริษัท Security-Plus นิติบุคคล",
        dueDate: "10/03/2569",
        dateCreated: "01/01/2568",
        updatedDate: "10/03/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        assignedProcessor: { name: "นายสมชาย ใจดี", assignedDate: "02/01/2568", processorStatus: "เสร็จสมบูรณ์", documentTitle: "บันทึกประวัติผู้มาติดต่อ" },
        title: "นาย", firstName: "มานะ", lastName: "อดทน",
        address: "สมุทรปราการ", email: "mana@security.co.th", phoneNumber: "02-333-2222",
        dataSubjectName: "บุคคลภายนอกที่มาติดต่อ", processingActivity: "Visitor Registration", 
        purpose: "เพื่อรักษาความปลอดภัยภายในอาคาร", personalData: "ภาพถ่ายใบหน้า, ทะเบียนรถ",
        dataCategories: ["contact"], dataType: DataType.Sensitive, 
        storedDataTypes: ["เลขประจำตัวประชาชน", "ชื่อ - นามสกุล"],
        collectionMethod: CollectionMethod.HardCopy, dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานประโยชน์โดยชอบธรรม", 
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { 
            storageType: CollectionMethod.HardCopy, 
            method: ["สมุดบันทึกหน้าป้อมยาม"], 
            duration: 30, 
            unit: RetentionUnit.Day, 
            accessControl: "เจ้าหน้าที่หัวหน้ารักษาความปลอดภัย", 
            deletionMethod: "ทำลายทิ้งทุกสิ้นเดือน" 
        },
        exemptionDisclosure: "ขอดูย้อนหลังโดยเจ้าหน้าที่ตำรวจกรณีมีเหตุอาชญากรรม",
        securityMeasures: { physical: "Lock box, CCTV coverage" }
    },
    {
        id: "DFT-2026-02",
        documentName: "ข้อมูลการส่งออกพัสดุ",
        status: RopaStatus.Draft,
        dateCreated: "10/03/2026",
        updatedDate: "16/03/2026",
        title: "นาย", firstName: "สืบพงศ์", lastName: "สายส่ง",
        address: "บางนา กรุงเทพฯ", email: "subpong@delivery.com", phoneNumber: "085-555-5555",
        dataSubjectName: "ผู้ส่งและผู้รับพัสดุ", processingActivity: "Logistics Tracking", 
        purpose: "เพื่อติดตามสถานะการจัดส่งพัสดุ", personalData: "พิกัด GPS, ลายเซ็นรับของ",
        dataCategories: ["customer"], dataType: DataType.General, 
        storedDataTypes: ["ชื่อ - นามสกุล", "เบอร์โทรศัพท์", "อื่นๆ"],
        storedDataTypesOther: "ลายเซ็นดิจิทัล",
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานสัญญา", 
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { 
            storageType: CollectionMethod.SoftFile, 
            method: ["Delivery App DB"], 
            duration: 1, 
            unit: RetentionUnit.Year, 
            accessControl: "Dispatcher", 
            deletionMethod: "Soft delete from DB" 
        },
        exemptionDisclosure: "ไม่มี",
        securityMeasures: { technical: "Mobile App Encryption" }
    },
    {
        id: "DFT-2026-01",
        documentName: "ฐานข้อมูลผู้รับเหมาช่วง",
        status: RopaStatus.Draft,
        dateCreated: "12/03/2569",
        updatedDate: "15/03/2569",
        title: "นางสาว", firstName: "ใจดี", lastName: "มีวาสนา",
        address: "ปทุมธานี", email: "jaidee@contractor.com", phoneNumber: "086-666-6666",
        dataSubjectName: "บุคคลสาธารณะและนิติบุคคล", processingActivity: "Vendor Management", 
        purpose: "เพื่อคัดเลือกและจัดจ้างผู้จัดการภายนอก", personalData: "โปรไฟล์งาน, ราคาเสนอ",
        dataCategories: ["partner"], dataType: DataType.General, 
        storedDataTypes: ["ชื่อ - นามสกุล", "เลขประจำตัวผู้เสียภาษี"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: true },
        legalBasis: "ฐานสัญญา", 
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { 
            storageType: CollectionMethod.SoftFile, 
            method: ["Procurement System"], 
            duration: 5, 
            unit: RetentionUnit.Year, 
            accessControl: "Procurement Officer", 
            deletionMethod: "Remove from Active System" 
        },
        exemptionDisclosure: "ไม่มี",
        securityMeasures: { organizational: "Vendor Code of Conduct" }
    }
];
