import { OwnerRecord } from "@/types/dataOwner";
import { RopaStatus, DataType, CollectionMethod, RetentionUnit } from "@/types/enums";

export const mockOwnerRecords: OwnerRecord[] = [
    {
        id: "ROPA-2026-0001",
        documentName: "ระบบ e-Logistics Gateway (พิธีการศุลกากร)",
        status: RopaStatus.Rejected,
        dateCreated: "26/03/2026, 14:30",
        title: "นาย",
        firstName: "ธนากร",
        lastName: "วัฒนศิริ",
        address: "123 ถ.สุขุมวิท แขวงคลองเตย เขตคลองเตย กรุงเทพมหานคร 10110",
        email: "thanakorn.w@example.co.th",
        phoneNumber: "0812345678",
        dataSubjectName: "ลูกค้าและผู้ใช้บริการระบบพิธีการศุลกากรออนไลน์",
        processingActivity: "การประมวลผลข้อมูลพิธีการนำเข้า-ส่งออกสินค้า",
        purpose: "เพื่อดำเนินพิธีการศุลกากรและส่งข้อมูลให้กรมศุลกากร",
        personalData: "ชื่อ-นามสกุล, ที่อยู่, เลขบัตรประชาชน, ข้อมูลธุรกิจ",
        dataCategories: ["customer", "partner"],
        dataType: DataType.General,
        storedDataTypes: ["ชื่อ-นามสกุล", "ที่อยู่", "เลขประจำตัวประชาชน", "ข้อมูลธุรกิจ"],
        storedDataTypesOther: "",
        collectionMethod: CollectionMethod.SoftFile,
        dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานสัญญา (Contract) - จำเป็นสำหรับการดำเนินพิธีการศุลกากร",
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: {
            storageType: CollectionMethod.SoftFile,
            method: ["ระบบฐานข้อมูล", "Cloud Storage"],
            duration: 5,
            unit: RetentionUnit.Year,
            accessControl: "เข้าถึงได้เฉพาะเจ้าหน้าที่ที่ได้รับมอบหมายเท่านั้น ผ่านระบบ SSO",
            deletionMethod: "ลบข้อมูลออกจากระบบและทำลายสำเนาฉบับกระดาษ"
        },
        exemptionDisclosure: "ส่งข้อมูลให้กรมศุลกากรตามกฎหมาย ไม่มีการเปิดเผยให้บุคคลภายนอกอื่น",
        securityMeasures: {
            organizational: "มีนโยบายความปลอดภัยข้อมูลที่ได้รับการอนุมัติจากผู้บริหาร",
            technical: "ใช้การเข้ารหัส AES-256 สำหรับข้อมูลที่จัดเก็บ",
            physical: "ห้องเซิร์ฟเวอร์มีระบบล็อคและกล้องวงจรปิด",
            accessControl: "ระบบ Role-Based Access Control (RBAC)",
            responsibility: "มีเจ้าหน้าที่คุ้มครองข้อมูลส่วนบุคคล (DPO) ที่แต่งตั้งแล้ว",
            audit: "ตรวจสอบ Log การเข้าถึงข้อมูลทุก 3 เดือน"
        },
        suggestions: [
            {
                id: "s1",
                section: "ส่วนที่ 2 : วัตถุประสงค์การประมวลผล",
                sectionId: 2,
                comment: "วัตถุประสงค์ในการเก็บข้อมูลเพื่อส่งต่อกรมศุลกากรมีความชัดเจนแล้ว แต่กรุณาเพิ่มรายละเอียดการจัดเก็บ log การเข้าถึงระบบ (Access Log) ให้ครอบคลุมตามมาตรฐานความปลอดภัยข้อมูล",
                reviewer: "วิริยา พรหมรักษ์",
                date: "26/03/2026, 14:30",
                role: "owner",
                status: "pending"
            },
            {
                id: "s2",
                section: "ส่วนที่ 4 : ระยะเวลาการเก็บรักษา",
                sectionId: 4,
                comment: "ระยะเวลาการเก็บรักษาข้อมูลชุดนี้ต้องสอดคล้องกับระเบียบของกรมศุลกากร (ปกติ 5 ปี) กรุณาตรวจสอบและอ้างอิงข้อเขียนทางกฎหมายให้ชัดเจน",
                reviewer: "วิริยา พรหมรักษ์",
                date: "26/03/2026, 14:30",
                role: "owner",
                status: "pending"
            }
        ]
    },
    {
        id: "ROPA-2026-0002",
        documentName: "ระบบ e-Tax Invoice & e-Receipt",
        status: RopaStatus.Submitted,
        dateCreated: "20/03/2026, 09:15",
        title: "นางสาว",
        firstName: "กัญญา",
        lastName: "มณีรัตน์",
        address: "456 ถ.รัชดาภิเษก แขวงลาดยาว เขตจตุจักร กรุงเทพมหานคร 10900",
        email: "kanya.m@example.co.th",
        phoneNumber: "0898765432",
        dataSubjectName: "ลูกค้าองค์กรที่ใช้บริการออกใบกำกับภาษีอิเล็กทรอนิกส์",
        processingActivity: "การออกและจัดเก็บใบกำกับภาษีอิเล็กทรอนิกส์ตามระบบ e-Tax ของสรรพากร",
        purpose: "เพื่อออกใบกำกับภาษีตามข้อกำหนดของกรมสรรพากร และจัดเก็บหลักฐานทางบัญชี",
        personalData: "ชื่อบริษัท, เลขประจำตัวผู้เสียภาษี, ที่อยู่จดทะเบียน",
        dataCategories: ["customer", "partner"],
        dataType: DataType.General,
        storedDataTypes: ["ชื่อ-นามสกุล", "ที่อยู่", "เลขประจำตัวผู้เสียภาษี"],
        storedDataTypesOther: "",
        collectionMethod: CollectionMethod.SoftFile,
        dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานกฎหมาย (Legal Obligation) - ตามประมวลรัษฎากร มาตรา 86/4",
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: {
            isTransfer: true,
            country: "สิงคโปร์",
            companyName: "Amazon Web Services (AWS) Singapore",
            transferMethod: "Cloud Storage สำรองข้อมูล",
            protectionStandard: "ISO 27001, SOC 2 Type II",
            exception: "ไม่มีข้อยกเว้น — เป็นไปตามมาตรฐานสากล"
        },
        retention: {
            storageType: CollectionMethod.SoftFile,
            method: ["Cloud Database", "Automated Backup"],
            duration: 5,
            unit: RetentionUnit.Year,
            accessControl: "เข้าถึงได้เฉพาะเจ้าหน้าที่บัญชีและไอทีที่ได้รับสิทธิ์",
            deletionMethod: "ลบข้อมูลออกจาก Cloud Storage หลังหมดระยะเวลา"
        },
        exemptionDisclosure: "ส่งข้อมูลให้กรมสรรพากรผ่านระบบ e-Filing เท่านั้น",
        securityMeasures: {
            organizational: "มีแผนป้องกันและตอบสนองต่อเหตุการณ์ละเมิดข้อมูล",
            technical: "การเข้ารหัส TLS 1.3 สำหรับข้อมูลระหว่างทาง",
            physical: "Data Center ได้รับการรับรอง Tier III",
            accessControl: "Multi-Factor Authentication สำหรับทุก Account",
            responsibility: "ทีม IT Security รับผิดชอบการจัดการข้อมูล",
            audit: "ตรวจสอบ Penetration Testing ทุก 6 เดือน"
        },
        suggestions: [
            {
                id: "s3",
                section: "ส่วนที่ 5 : การส่งข้อมูลไปต่างประเทศ",
                sectionId: 5,
                comment: "กรณีมีการใช้ Cloud Storage ของ AWS (Singapore Region) สำหรับสำรองข้อมูลใบกำกับภาษี กรุณาแนบเอกสารรับรองมาตรฐานการคุ้มครองข้อมูลส่วนบุคคลของ Cloud Provider",
                reviewer: "วิริยา พรหมรักษ์",
                date: "20/03/2026, 14:30",
                role: "processor",
                statusLabel: "เสร็จสมบูรณ์",
                status: "fixed"
            },
            {
                id: "s4",
                section: "ส่วนที่ 6 : มาตรการรักษาความปลอดภัย",
                sectionId: 6,
                comment: "กรุณาระบุมาตรการในการเข้ารหัสข้อมูล (Encryption) สำหรับข้อมูลส่วนบุคคลที่ปรากฏบนใบกำกับภาษีขณะจัดเก็บ (At Rest) เพื่อให้สอดคล้องกับ ISMS ของบริษัท",
                reviewer: "วิริยา พรหมรักษ์",
                date: "20/03/2026, 14:30",
                role: "processor",
                statusLabel: "ไม่เสร็จสมบูรณ์",
                status: "pending"
            }
        ]
    },
    {
        id: "ROPA-2026-0003",
        documentName: "ข้อมูลลูกค้าและประวัติการสั่งซื้อ",
        status: RopaStatus.Active,
        dateCreated: "15/03/2026, 16:45",
        title: "นาย",
        firstName: "ปิติ",
        lastName: "สุขสวรรค์",
        address: "789 ถ.พระราม 9 แขวงบางกะปิ เขตห้วยขวาง กรุงเทพมหานคร 10310",
        email: "piti.s@example.co.th",
        phoneNumber: "0876543210",
        dataSubjectName: "ลูกค้าของบริษัท",
        processingActivity: "การจัดเก็บและประมวลผลข้อมูลการสั่งซื้อสินค้าและบริการ",
        purpose: "เพื่อดำเนินการจัดส่งสินค้า ออกใบเสร็จ และให้บริการหลังการขาย",
        personalData: "ชื่อ, ที่อยู่, เบอร์โทรศัพท์, อีเมล, ประวัติการสั่งซื้อ",
        dataCategories: ["customer"],
        dataType: DataType.General,
        storedDataTypes: ["ชื่อ-นามสกุล", "ที่อยู่", "เบอร์โทรศัพท์", "อีเมล"],
        storedDataTypesOther: "",
        collectionMethod: CollectionMethod.SoftFile,
        dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานสัญญา (Contract) - การซื้อขายสินค้าและบริการ",
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: {
            storageType: CollectionMethod.SoftFile,
            method: ["ฐานข้อมูล MySQL", "การสำรองข้อมูลอัตโนมัติ"],
            duration: 3,
            unit: RetentionUnit.Year,
            accessControl: "พนักงานฝ่ายขายและบริการลูกค้าเข้าถึงได้ผ่านระบบ CRM",
            deletionMethod: "ลบข้อมูลออกจากฐานข้อมูลและ Backup หลังหมดระยะเวลา"
        },
        exemptionDisclosure: "ส่งที่อยู่จัดส่งให้บริษัทขนส่งเท่านั้น ภายใต้สัญญาการประมวลผลข้อมูล",
        securityMeasures: {
            organizational: "นโยบายการรักษาความลับของข้อมูลลูกค้า",
            technical: "การเข้ารหัส HTTPS และ Database Encryption",
            physical: "ระบบควบคุมการเข้าออกห้องเซิร์ฟเวอร์ด้วย Key Card",
            accessControl: "ระบบ Permission ตาม Role ของพนักงานแต่ละคน",
            responsibility: "ผู้จัดการฝ่าย IT รับผิดชอบโดยตรง",
            audit: "ตรวจสอบ Access Log ทุกเดือน"
        },
        assignedProcessor: {
            name: "บริษัท ABC Logistics จำกัด",
            assignedDate: "26/03/2026, 16:30",
            documentTitle: "ข้อมูลลูกค้าและประวัติการสั่งซื้อ (ส่วนประมวลผลข้อมูล)"
        }
    },
    {
        id: "ROPA-2026-0004",
        documentName: "การจัดเก็บข้อมูลบุคลากร HR",
        status: RopaStatus.Active,
        dateCreated: "10/03/2026, 14:00",
        title: "นางสาว",
        firstName: "มาลี",
        lastName: "ดอกไม้",
        address: "321 ถ.ลาดพร้าว แขวงลาดพร้าว เขตลาดพร้าว กรุงเทพมหานคร 10230",
        email: "malee.d@example.co.th",
        phoneNumber: "0823456789",
        dataSubjectName: "พนักงานและอดีตพนักงานขององค์กร",
        processingActivity: "การบริหารจัดการข้อมูลทรัพยากรบุคคล",
        purpose: "การจ้างงาน การจ่ายเงินเดือน การประเมินผล และการบริหารสวัสดิการ",
        personalData: "ชื่อ, ที่อยู่, เลขบัตรประชาชน, ประวัติการทำงาน, ข้อมูลสุขภาพ",
        dataCategories: ["employee"],
        dataType: DataType.Sensitive,
        storedDataTypes: ["ชื่อ-นามสกุล", "ที่อยู่", "เลขประจำตัวประชาชน", "ข้อมูลสุขภาพ"],
        storedDataTypesOther: "ประวัติการทำงาน, ข้อมูลเงินเดือน",
        collectionMethod: CollectionMethod.HardCopy,
        dataSource: { direct: true, indirect: true },
        legalBasis: "ฐานสัญญาจ้างงาน และฐานกฎหมายแรงงาน",
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: {
            storageType: CollectionMethod.HardCopy,
            method: ["แฟ้มเอกสาร", "ระบบ HR Software"],
            duration: 10,
            unit: RetentionUnit.Year,
            accessControl: "เข้าถึงได้เฉพาะ HR Manager และผู้บริหารที่ได้รับอนุมัติ",
            deletionMethod: "ทำลายเอกสารกระดาษด้วยเครื่องทำลายเอกสาร และลบข้อมูลดิจิทัล"
        },
        exemptionDisclosure: "ส่งข้อมูลให้สำนักงานประกันสังคมและกรมสรรพากรตามที่กฎหมายกำหนด",
        securityMeasures: {
            organizational: "นโยบาย HR Data Privacy ที่ผ่านการอนุมัติจากคณะกรรมการบริษัท",
            technical: "ระบบ HR Software ที่มีการเข้ารหัสข้อมูล",
            physical: "ตู้เก็บเอกสารล็อคกุญแจ ในห้องที่มีการควบคุมการเข้าถึง",
            accessControl: "สิทธิ์เข้าถึงตามหน้าที่ความรับผิดชอบ",
            responsibility: "HR Director รับผิดชอบโดยตรง",
            audit: "ตรวจสอบทุกปี"
        }
    },
    {
        id: "ROPA-2026-0005",
        documentName: "ระบบคุกกี้และการตลาดออนไลน์",
        status: RopaStatus.Draft,
        dateCreated: "05/04/2026, 10:30",
        title: "นาย",
        firstName: "วีระ",
        lastName: "ชาญศิลป์",
        address: "99 ถ.สีลม แขวงสีลม เขตบางรัก กรุงเทพมหานคร 10500",
        email: "veera.c@example.co.th",
        phoneNumber: "0845678901",
        dataSubjectName: "ผู้เยี่ยมชมเว็บไซต์และผู้รับการตลาดออนไลน์",
        processingActivity: "การเก็บรวบรวมข้อมูลพฤติกรรมการใช้งานเว็บไซต์ผ่านคุกกี้",
        purpose: "เพื่อวิเคราะห์พฤติกรรมผู้ใช้และปรับปรุงประสบการณ์การใช้งานเว็บไซต์",
        personalData: "IP Address, Cookie ID, ประวัติการเข้าชมหน้าเว็บ",
        dataCategories: ["customer"],
        dataType: DataType.General,
        storedDataTypes: ["อีเมล"],
        storedDataTypesOther: "IP Address, Cookie Data, ข้อมูลพฤติกรรมการใช้งาน",
        collectionMethod: CollectionMethod.SoftFile,
        dataSource: { direct: false, indirect: true },
        legalBasis: "ฐานความยินยอม (Consent) - ผ่านระบบ Cookie Consent Banner",
        minorConsent: { under10: false, age10to20: true, none: false },
        internationalTransfer: {
            isTransfer: true,
            country: "สหรัฐอเมริกา",
            companyName: "Google Analytics / Meta Pixel",
            transferMethod: "API Integration",
            protectionStandard: "Standard Contractual Clauses (SCCs)",
            exception: "ใช้ SCCs ตามมาตรา 28 แห่ง PDPA"
        },
        retention: {
            storageType: CollectionMethod.SoftFile,
            method: ["Analytics Platform", "CRM Database"],
            duration: 1,
            unit: RetentionUnit.Year,
            accessControl: "ทีมการตลาดดิจิทัลเข้าถึงได้ผ่านระบบ Analytics Dashboard",
            deletionMethod: "ลบข้อมูลอัตโนมัติเมื่อหมดอายุ Cookie"
        },
        exemptionDisclosure: "ข้อมูล Aggregate ไม่ระบุตัวตนอาจแชร์กับ Partner ทางการตลาด",
        securityMeasures: {
            organizational: "นโยบายคุกกี้และความเป็นส่วนตัวที่เผยแพร่บนเว็บไซต์",
            technical: "การเข้ารหัสข้อมูล Cookie และการ Anonymize ข้อมูลก่อนวิเคราะห์",
            physical: "N/A - ข้อมูลจัดเก็บบน Cloud",
            accessControl: "สิทธิ์เข้าถึง Analytics ตาม Role",
            responsibility: "Digital Marketing Manager",
            audit: "ทบทวน Cookie Policy ทุก 6 เดือน"
        }
    }
];
