import { OwnerRecord } from "@/types/dataOwner";
import { RopaProcessorRecord } from "@/types/dataProcessor";
import { RopaStatus, DataType, CollectionMethod, RetentionUnit } from "@/types/enums";

/**
 * Standardized DPO Mock Records (RP-2026-01 to RP-2026-13)
 * Optimized for full DPO Audit detail demo.
 */

export const mockOwnerRecords: OwnerRecord[] = [
    {
        id: "RP-2026-01",
        documentName: "บันทึกการเข้าออกคลาวด์เซิร์ฟเวอร์",
        status: RopaStatus.Processing,
        workflow: "processing",
        department: "แผนก IT",
        processorCompany: "บริษัท IT Security Pro",
        dueDate: "15/03/2569",
        dateCreated: "01/03/2569",
        updatedDate: "14/03/2569",
        processingStatus: { doStatus: "done", dpStatus: "pending" },
        assignedProcessor: { name: "นายณัฐวุฒิ ศรีสวัสดิ์", assignedDate: "05/03/2569", processorStatus: "ไม่เสร็จสมบูรณ์", documentTitle: "บันทึกการเข้าออกคลาวด์เซิร์ฟเวอร์" },
        title: "นาย", firstName: "ปิติ", lastName: "สุขสวรรค์",
        address: "อาคารซอฟต์แวร์พาร์ค นนทบุรี",
        email: "piti.s@itsecurity.co.th",
        phoneNumber: "02-123-4567",
        dataCategories: ["employee", "admin"],
        dataSubjectName: "ผู้ดูแลระบบ (Admin)", processingActivity: "System Monitoring",
        purpose: "เพื่อรักษาความมั่นคงปลอดภัยทางสารสนเทศ", personalData: "IP Address, Login Log",
        dataType: DataType.General, storedDataTypes: ["อื่นๆ"], storedDataTypesOther: "IP Address, MAC Address",
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: false, indirect: true },
        legalBasis: "ฐานประโยชน์โดยชอบธรรม",
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Cloud Logs"], duration: 90, unit: RetentionUnit.Day, accessControl: "IT Admin", deletionMethod: "Auto-overwrite" },
        exemptionDisclosure: "ไม่มีการใช้หรือเปิดเผยข้อมูลที่ได้รับยกเว้น",
        securityMeasures: { technical: "IDS/IPS, Log Integrity Check", audit: "SIEM Dashboard" },
        riskAssessment: { level: "สูง", probability: 3, impact: 3, total: 9 },
    },
    {
        id: "RP-2026-02",
        documentName: "ข้อมูลธุรกรรมการซื้อขาย",
        status: RopaStatus.Processing,
        workflow: "processing",
        department: "แผนกขาย",
        processorCompany: "บริษัท บัญชีดี จำกัด",
        dueDate: "18/03/2569",
        dateCreated: "01/03/2569",
        updatedDate: "12/03/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        assignedProcessor: { name: "นางสาวพิมพ์ชนก วัฒนากุล", assignedDate: "05/03/2569", processorStatus: "เสร็จสมบูรณ์", documentTitle: "ข้อมูลธุรกรรมการซื้อขาย" },
        title: "นางสาว", firstName: "กัญญา", lastName: "มณีรัตน์",
        address: "123 อาคารพญาไทพลาซ่า กรุงเทพฯ", email: "kanya.m@accounting.co.th",
        phoneNumber: "02-987-6543",
        dataCategories: ["partner"],
        dataSubjectName: "คู่ค้าและซัพพลายเออร์", processingActivity: "Record-to-Report",
        purpose: "เพื่อจัดทำบัญชีและเสียภาษีตามกฎหมาย", personalData: "ชื่อบริษัท, เลขประจำตัวผู้เสียภาษี",
        dataType: DataType.General, storedDataTypes: ["เลขประจำตัวประชาชน", "ชื่อ - นามสกุล"],
        collectionMethod: CollectionMethod.HardCopy, dataSource: { direct: true, indirect: true },
        legalBasis: "ฐานการปฏิบัติตามกฎหมาย",
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.HardCopy, method: ["Safe Box"], duration: 10, unit: RetentionUnit.Year, accessControl: "Finance Manager", deletionMethod: "Shredder" },
        exemptionDisclosure: "การส่งข้อมูลให้กรมสรรพากร",
        securityMeasures: { physical: "ห้องเก็บเอกสารล็อคกุญแจ 2 ชั้น", audit: "บันทึกการเข้า-ออกห้องเก็บเอกสาร" },
        riskAssessment: { level: "ต่ำ", probability: 1, impact: 2, total: 2 },
    },
    {
        id: "RP-2026-03",
        documentName: "ข้อมูลลูกค้าเพื่อการตลาด",
        status: RopaStatus.Processing,
        workflow: "processing",
        department: "แผนกการตลาด",
        processorCompany: "บริษัท NetBay Marketing",
        dueDate: "20/03/2569",
        dateCreated: "01/03/2569",
        updatedDate: "10/03/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        assignedProcessor: { name: "นายกิตติพงศ์ สุวรรณชัย", assignedDate: "05/03/2569", processorStatus: "เสร็จสมบูรณ์", documentTitle: "ข้อมูลลูกค้าเพื่อการตลาด" },
        title: "นาย", firstName: "ธนากร", lastName: "วัฒนศิริ",
        address: "99/1 ถนนวิภาวดีรังสิต กรุงเทพฯ", email: "thanakorn.w@netbay.co.th",
        phoneNumber: "02-555-5555",
        dataCategories: ["customer"],
        dataSubjectName: "ลูกค้าทั่วไป", processingActivity: "การส่งข่าวสารประชาสัมพันธ์",
        purpose: "เพื่อแจ้งสิทธิประโยชน์และกิจกรรมทางการตลาด", personalData: "ชื่อ, อีเมล, เบอร์โทรศัพท์",
        dataType: DataType.General, storedDataTypes: ["ชื่อ - นามสกุล", "อีเมล", "เบอร์โทรศัพท์"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานความยินยอม",
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["AWS S3"], duration: 5, unit: RetentionUnit.Year, accessControl: "Marketing Team", deletionMethod: "ลบไฟล์ถาวร" },
        exemptionDisclosure: "ไม่มี",
        securityMeasures: { technical: "Encryption at rest", accessControl: "Role-based Access" },
        riskAssessment: { level: "ปานกลาง", probability: 2, impact: 3, total: 6 },
    },
    {
        id: "RP-2026-04",
        documentName: "การดูแลข้อมูลธุรกรรมทางการเงิน",
        status: RopaStatus.ReviewPending,
        workflow: "sent_dpo",
        department: "แผนกบัญชี",
        processorCompany: "บริษัท PayCheck Thailand",
        dueDate: "01/04/2569",
        dateCreated: "01/03/2569",
        updatedDate: "20/03/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        assignedProcessor: { name: "นางสาวศิริพร บุญเหลือ", assignedDate: "02/03/2569", processorStatus: "เสร็จสมบูรณ์", documentTitle: "การดูแลข้อมูลธุรกรรมทางการเงิน" },
        title: "นางสาว", firstName: "รัชนี", lastName: "มีเงิน",
        address: "บางนา กรุงเทพฯ", email: "rajanee@netbay.co.th",
        phoneNumber: "02-333-4444",
        dataCategories: ["customer", "employee"],
        dataSubjectName: "ลูกค้าและพนักงาน", processingActivity: "Financial Transaction Audit",
        purpose: "เพื่อตรวจสอบความถูกต้องของธุรกรรมทางการเงิน", personalData: "ชื่อ, เลขที่บัญชี, ยอดชำระ",
        dataType: DataType.General, storedDataTypes: ["ชื่อ - นามสกุล", "เลขที่บัญชีธนาคาร"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานการปฏิบัติตามสัญญา",
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Secure Storage"], duration: 7, unit: RetentionUnit.Year, accessControl: "Accounting Head", deletionMethod: "Database Purge" },
        exemptionDisclosure: "รายงานบัญชีต่อหน่วยงานกำกับดูแล",
        securityMeasures: { technical: "Database Encryption", organizational: "Access Review Policy" },
        riskAssessment: { level: "ต่ำ", probability: 1, impact: 3, total: 3 },
    },
    {
        id: "RP-2026-05",
        documentName: "การจัดเก็บข้อมูลผู้ใช้งานระบบ",
        status: RopaStatus.DeletePending,
        workflow: "delete_pending",
        department: "แผนก IT",
        processorCompany: "บริษัท Cloud-Solution Ltd.",
        dueDate: "25/03/2569",
        dateCreated: "01/01/2569",
        updatedDate: "15/03/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        assignedProcessor: { name: "นายอรรถพล เมืองไทย", assignedDate: "05/01/2569", processorStatus: "เสร็จสมบูรณ์", documentTitle: "การจัดเก็บข้อมูลผู้ใช้งานระบบ" },
        title: "นาย", firstName: "อรรถพล", lastName: "เรืองศรี",
        address: "กรุงเทพฯ", email: "attapol@cloudsol.th",
        phoneNumber: "02-111-2222",
        dataCategories: ["customer"],
        dataSubjectName: "ผู้ใช้งานระบบ CRM", processingActivity: "User Profile Management",
        purpose: "เพื่อจัดการข้อมูลสมาชิกและสิทธิการเข้าใช้งาน", personalData: "Username, Password Hash, อีเมล",
        dataType: DataType.General, storedDataTypes: ["ชื่อ - นามสกุล", "อีเมล"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานสัญญา",
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Cloud DB"], duration: 1, unit: RetentionUnit.Year, accessControl: "IT System Owner", deletionMethod: "Delete from DB" },
        exemptionDisclosure: "ไม่มี",
        securityMeasures: { technical: "Hash passwords, SSL", accessControl: "Token-based Auth" },
        riskAssessment: { level: "ปานกลาง", probability: 1, impact: 5, total: 5 },
    },
    {
        id: "RP-2026-06",
        documentName: "การบริหารจัดการข้อมูลการบริการ",
        status: RopaStatus.DeletePending,
        workflow: "delete_pending",
        department: "แผนกบริการลูกค้า",
        processorCompany: "บริษัท Security-Plus นิติบุคคล",
        dueDate: "10/03/2569",
        dateCreated: "01/01/2568",
        updatedDate: "10/03/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        assignedProcessor: { name: "นายสมชาย ใจดี", assignedDate: "02/01/2568", processorStatus: "เสร็จสมบูรณ์", documentTitle: "การบริหารจัดการข้อมูลการบริการ" },
        title: "นาย", firstName: "มานะ", lastName: "อดทน",
        address: "สมุทรปราการ", email: "mana@security.co.th",
        phoneNumber: "02-444-5555",
        dataCategories: ["customer"],
        dataSubjectName: "ลูกค้าที่รับบริการ", processingActivity: "Customer Service Support",
        purpose: "เพื่อบันทึกประวัติการรับบริการและแก้ปัญหาการใช้งาน", personalData: "ชื่อ, เบอร์โทรศัพท์, ประวัติแจ้งปัญหา",
        dataType: DataType.General, storedDataTypes: ["ชื่อ - นามสกุล", "เบอร์โทรศัพท์"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานประโยชน์โดยชอบธรรม",
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["System Archives"], duration: 3, unit: RetentionUnit.Year, accessControl: "CS Manager", deletionMethod: "De-identification" },
        exemptionDisclosure: "การพิสูจน์ตัวตนในกรณีพิพาท",
        securityMeasures: { technical: "Data Masking", organizational: "Privacy Policy" },
        riskAssessment: { level: "ต่ำ", probability: 1, impact: 2, total: 2 },
    },
    {
        id: "RP-2026-07",
        documentName: "ข้อมูลการสำรวจตลาด",
        status: RopaStatus.DeletePending,
        workflow: "delete_pending",
        department: "แผนกวิจัยตลาด",
        dueDate: "15/04/2569",
        dateCreated: "01/01/2569",
        updatedDate: "15/01/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        title: "นาย", firstName: "สมคิด", lastName: "มานะชีพ",
        address: "กรุงเทพฯ", email: "somkid@research.co.th",
        phoneNumber: "02-999-8888",
        dataCategories: ["individual"],
        dataSubjectName: "กลุ่มเป้าหมายการสำรวจ", processingActivity: "Market Research Survey",
        purpose: "เพื่อวิเคราะห์แนวโน้มตลาดและความต้องการผู้บริโภค", personalData: "เพศ, อายุ, ความชอบผลิตภัณฑ์",
        dataType: DataType.General, storedDataTypes: ["เพศ", "ช่วงอายุ"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานความยินยอม",
        minorConsent: { under10: false, age10to20: true, none: false },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Research Server"], duration: 1, unit: RetentionUnit.Year, accessControl: "Market Research Lead", deletionMethod: "Delete from Server" },
        exemptionDisclosure: "ไม่มี",
        securityMeasures: { organizational: "Retention Policy for Surveys", technical: "Anonymization" },
        riskAssessment: { level: "ต่ำ", probability: 1, impact: 1, total: 1 },
    },
    {
        id: "RP-2026-08",
        documentName: "การจัดการคุกกี้",
        status: RopaStatus.Processing,
        workflow: "processing",
        department: "แผนก IT",
        dueDate: "20/04/2569",
        dateCreated: "10/01/2569",
        updatedDate: "20/03/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        title: "นาย", firstName: "กิตติ", lastName: "สุขใจ",
        address: "นนทบุรี", email: "kitti@it.com",
        phoneNumber: "02-777-6666",
        dataCategories: ["contact"],
        dataSubjectName: "ผู้เยี่ยมชมเว็บไซต์", processingActivity: "Cookie Tracking",
        purpose: "เพื่อวิเคราะห์การใช้งานเว็บไซต์และปรับปรุงประสบการณ์ผู้ใช้", personalData: "Cookie ID, Browser Settings",
        dataType: DataType.General, storedDataTypes: ["อื่นๆ"], storedDataTypesOther: "Cookie ID",
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: false, indirect: true },
        legalBasis: "ฐานความยินยอม",
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Web Server"], duration: 1, unit: RetentionUnit.Year, accessControl: "Web Admin", deletionMethod: "Auto-clear" },
        exemptionDisclosure: "ไม่มี",
        securityMeasures: { technical: "HTTPS, Cookie Security Flags" },
        riskAssessment: { level: "ต่ำ", probability: 1, impact: 1, total: 1 },
    },
    {
        id: "RP-2026-09",
        documentName: "ล็อกระบบเข้าถึงข้อมูล",
        status: RopaStatus.DeletePending,
        workflow: "delete_pending",
        department: "แผนก Security",
        dueDate: "15/05/2569",
        dateCreated: "01/02/2569",
        updatedDate: "15/03/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        title: "นาย", firstName: "ยาม", lastName: "เฝ้าหน้าประตู",
        address: "กรุงเทพฯ", email: "guard@secure.co.th",
        phoneNumber: "02-121-1212",
        dataCategories: ["employee"],
        dataSubjectName: "พนักงานที่มีสิทธิ์เข้าถึงข้อมูล", processingActivity: "System Logging",
        purpose: "เพื่อรักษาความปลอดภัยและตรวจสอบย้อนหลังการเข้าถึงข้อมูล", personalData: "Log ID, Access Time",
        dataType: DataType.General, storedDataTypes: ["อื่นๆ"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: false, indirect: true },
        legalBasis: "ฐานประโยชน์โดยชอบธรรม",
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Security Logs"], duration: 10, unit: RetentionUnit.Year, accessControl: "Security Officer", deletionMethod: "Overwrite" },
        exemptionDisclosure: "ข้อมูลพยานหลักฐานกรณีมีเหตุอาชญากรรม",
        securityMeasures: { technical: "Admin Log Monitoring", accessControl: "Privileged Access Management" },
        riskAssessment: { level: "ปานกลาง", probability: 2, impact: 2, total: 4 },
    },
    {
        id: "RP-2026-10",
        documentName: "นโยบายความเป็นส่วนตัว",
        status: RopaStatus.ReviewPending,
        workflow: "sent_dpo",
        department: "แผนกกฎหมาย",
        dueDate: "05/04/2569",
        dateCreated: "01/03/2569",
        updatedDate: "20/03/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        title: "นางสาว", firstName: "ยุติธรรม", lastName: "เสมอภาค",
        address: "กรุงเทพฯ", email: "legal@company.co.th",
        phoneNumber: "02-131-4151",
        dataCategories: ["customer", "partner", "employee"],
        dataSubjectName: "ผู้ใช้บริการทั้งหมด", processingActivity: "Privacy Policy Update",
        purpose: "เพื่อแจ้งให้เจ้าของข้อมูลทราบถึงรายละเอียดการประมวลผล", personalData: "ไม่มีข้อมูลส่วนบุคคลโดยตรงในนโยบาย",
        dataType: DataType.General, storedDataTypes: ["อื่นๆ"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานกฎหมาย",
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Legal Drive"], duration: 50, unit: RetentionUnit.Year, accessControl: "Legal Counsel", deletionMethod: "Archive" },
        exemptionDisclosure: "ไม่มี",
        securityMeasures: { organizational: "Retention Policy Compliance" },
        riskAssessment: { level: "ต่ำ", probability: 1, impact: 1, total: 1 },
    },
    {
        id: "RP-2026-11",
        documentName: "ข้อมูลแอปพลิเคชัน",
        status: RopaStatus.Processing,
        workflow: "processing",
        department: "แผนก Digital",
        dueDate: "30/05/2569",
        dateCreated: "01/01/2569",
        updatedDate: "01/04/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        title: "นาย", firstName: "ดีิจิทัล", lastName: "แม็กซ์",
        address: "ตึกจตุจักร", email: "max@app.co.th",
        phoneNumber: "02-555-9999",
        dataCategories: ["customer"],
        dataSubjectName: "สมาชิกแอปมือถือ", processingActivity: "Mobile Application Database",
        purpose: "เพื่อให้บริการผ่านแอปพลิเคชันมือถือ", personalData: "พิกัด, ข้อมูลเครื่องมือถือ",
        dataType: DataType.General, storedDataTypes: ["ชื่อ - นามสกุล", "พิกัด"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานสัญญา",
        minorConsent: { under10: false, age10to20: true, none: false },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["App Database"], duration: 5, unit: RetentionUnit.Year, accessControl: "App Developer", deletionMethod: "Cloud Purge" },
        exemptionDisclosure: "ไม่มี",
        securityMeasures: { technical: "Encryption, App Scanning", organizational: "Developer Standards" },
        riskAssessment: { level: "สูง", probability: 3, impact: 4, total: 12 },
    },
    {
        id: "RP-2026-12",
        documentName: "ระบบบริหารจัดการเงินเดือนพนักงาน",
        status: RopaStatus.ReviewPending,
        workflow: "sent_dpo",
        department: "แผนก HR",
        processorCompany: "บริษัท PayCheck Thailand",
        dueDate: "01/04/2569",
        dateCreated: "01/03/2569",
        updatedDate: "20/03/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        assignedProcessor: { name: "นางสาวศิริพร บุญเหลือ", assignedDate: "02/03/2569", processorStatus: "เสร็จสมบูรณ์", documentTitle: "ระบบบริหารจัดการเงินเดือนพนักงาน" },
        title: "นางสาว", firstName: "วิภา", lastName: "มหาทรัพย์",
        address: "เขตลาดพร้าว กรุงเทพฯ", email: "wipa@netbay.co.th",
        phoneNumber: "02-555-4444",
        dataCategories: ["employee"],
        dataSubjectName: "พนักงานประจำและสัญญาจ้าง", processingActivity: "Payroll Calculation",
        purpose: "เพื่อคำนวณเงินเดือนและนำส่งภาษี/ประกันสังคม", personalData: "ชื่อ, เลขที่บัญชีธนาคาร, เงินเดือน",
        dataType: DataType.General, storedDataTypes: ["ชื่อ - นามสกุล", "เลขประจำตัวประชาชน"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานการปฏิบัติตามกฎหมาย",
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["HR System"], duration: 10, unit: RetentionUnit.Year, accessControl: "HR Manager", deletionMethod: "Database Delete" },
        exemptionDisclosure: "นำส่งข้อมูลให้สำนักงานประกันสังคม",
        securityMeasures: { organizational: "HR Access Policy", technical: "Database Encryption" },
        riskAssessment: { level: "ต่ำ", probability: 1, impact: 3, total: 3 },
    },
    {
        id: "RP-2026-13",
        documentName: "ข้อมูลการจ้างงาน",
        status: RopaStatus.Processing,
        workflow: "processing",
        department: "แผนก Recruitment",
        dueDate: "15/06/2569",
        dateCreated: "01/02/2569",
        updatedDate: "15/04/2569",
        processingStatus: { doStatus: "done", dpStatus: "done" },
        title: "นาย", firstName: "ว่าจ้าง", lastName: "รุ่งเรือง",
        address: "กรุงเทพฯ", email: "hiring@company.co.th",
        phoneNumber: "02-111-2323",
        dataCategories: ["candidate"],
        dataSubjectName: "ผู้มาสมัครงาน", processingActivity: "Hiring and Interviewing",
        purpose: "เพื่อพิจารณาการจ้างงานและคัดเลือกบุคลากรใหม่", personalData: "ประวัติการศึกษา, CV, เบอร์ติดต่อ",
        dataType: DataType.General, storedDataTypes: ["ชื่อ - นามสกุล", "วุฒิการศึกษา"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        legalBasis: "ฐานความยินยอม",
        minorConsent: { under10: false, age10to20: false, none: true },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Recruitment Drive"], duration: 2, unit: RetentionUnit.Year, accessControl: "Recruiter", deletionMethod: "Clear files" },
        exemptionDisclosure: "ไม่มี",
        securityMeasures: { organizational: "Hiring Standards Policy" },
        riskAssessment: { level: "ต่ำ", probability: 1, impact: 3, total: 3 },
    }
];

export const mockProcessorRecords: RopaProcessorRecord[] = [
    {
        id: "RP-2026-04",
        ropaId: "RP-2026-04",
        documentName: "การดูแลข้อมูลธุรกรรมทางการเงิน",
        processorName: "บริษัท PayCheck Thailand",
        status: RopaStatus.ReviewPending,
        controllerName: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controllerAddress: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นาย", firstName: "ธนาวุฒิ", lastName: "ศรีสุข",
        address: "99 ถนนรัชดาภิเษก กรุงเทพฯ", email: "thanawut.s@paycheck.co.th",
        phoneNumber: "02-222-3333",
        processingActivity: "การตรวจสอบธุรกรรมทางการเงิน",
        purpose: "เพื่อตรวจสอบความถูกต้องของข้อมูลธุรกรรมตามคำสั่ง",
        personalData: "ชื่อ-นามสกุล, เลขประจำตัวประชาชน, เงินเดือน",
        dataCategories: ["customer", "employee"],
        dataType: DataType.General, storedDataTypes: ["ชื่อ - นามสกุล", "เลขที่บัญชีธนาคาร"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Cloud DB"], duration: 7, unit: RetentionUnit.Year, accessCondition: "Contractual Obligation", deletionMethod: "Permanent Delete" },
        legalBasis: "ฐานสัญญา",
        securityMeasures: { organizational: "MFA Authentication", technical: "Database Encryption" }
    },
    {
        id: "RP-2026-01",
        ropaId: "RP-2026-01",
        documentName: "การจัดการข้อมูลโครงข่าย",
        processorName: "บริษัท เน็ตเบย์ เทคโนโลยี จำกัด",
        status: RopaStatus.Approved,
        controllerName: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controllerAddress: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นาย", firstName: "สิทธิพล", lastName: "ว่องไว",
        address: "456 ถนนสุขุมวิท กรุงเทพฯ", email: "sittipon.v@netbaytech.co.th",
        phoneNumber: "02-555-6666",
        processingActivity: "การเชื่อมโยงระบบเครือข่าย",
        purpose: "เพื่อให้บริการเชื่อมต่อข้อมูลเสถียร",
        personalData: "ชื่อ-นามสกุล, ที่อยู่ IP",
        dataCategories: ["customer"],
        dataType: DataType.General, storedDataTypes: ["ชื่อ - นามสกุล", "ที่อยู่ IP"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: false, indirect: true },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Secure Server"], duration: 10, unit: RetentionUnit.Year, accessCondition: "Admin Only", deletionMethod: "Data Scrubbing" },
        legalBasis: "ฐานการปฏิบัติตามสัญญา",
        securityMeasures: { technical: "VPN Access", organizational: "ISMS Policy" }
    },
    {
        id: "RP-2026-02",
        ropaId: "RP-2026-02",
        documentName: "การกำกับดูแลข้อมูลธุรกรรม",
        processorName: "บริษัท ระบบการเงิน จำกัด",
        status: RopaStatus.ReviewPending,
        controllerName: "บริษัท ธนาคารพาณิชย์ จำกัด",
        controllerAddress: "555 ถนนพหลโยธิน กรุงเทพฯ",
        title: "นางสาว", firstName: "พรทิพย์", lastName: "รักษาดี",
        address: "789 ถนนรัชดาภิเษก กรุงเทพฯ", email: "porntip.r@financesys.co.th",
        phoneNumber: "02-987-6543",
        processingActivity: "การบันทึกรายการธุรกรรมประจำวัน",
        purpose: "เพื่อตรวจสอบความถูกต้องและป้องกันทุจริต",
        personalData: "ชื่อ, เลขบัญชี, ยอดเงิน",
        dataCategories: ["customer"],
        dataType: DataType.General, storedDataTypes: ["ชื่อ", "เลขบัญชี"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Bank Archive"], duration: 10, unit: RetentionUnit.Year, accessCondition: "Audit only", deletionMethod: "Secure Shredding (Digital)" },
        legalBasis: "ฐานกฎหมาย (Financial Laws)",
        securityMeasures: { technical: "Hardware Security Module (HSM)", organizational: "Compulsory Audit" }
    },
    {
        id: "RP-2026-03",
        ropaId: "RP-2026-03",
        documentName: "ข้อมูลลูกค้าเพื่อการตลาด",
        processorName: "บริษัท NetBay Marketing",
        status: RopaStatus.Processing,
        controllerName: "บริษัท เมนคอนโทรลเลอร์ จำกัด",
        controllerAddress: "99/1 ถนนวิภาวดีรังสิต",
        title: "นาย", firstName: "กิตติพงศ์", lastName: "สุวรรณชัย",
        address: "123 NetBay Company, Bangkok", email: "kittipong@netbay.co.th",
        phoneNumber: "02-123-1234",
        processingActivity: "การส่งข่าวสารประชาสัมพันธ์",
        purpose: "เพื่อแจ้งสิทธิประโยชน์และโฆษณา",
        personalData: "ชื่อ, อีเมล, เบอร์โทรศัพท์",
        dataCategories: ["customer"],
        dataType: DataType.General, storedDataTypes: ["ชื่อ - นามสกุล", "อีเมล", "เบอร์โทรศัพท์"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["AWS Storage"], duration: 5, unit: RetentionUnit.Year, accessCondition: "Consent dependent", deletionMethod: "Delete from DB" },
        legalBasis: "ฐานความยินยอม",
        securityMeasures: { technical: "AES-256 Encryption", accessControl: "2FA Required" }
    },
    {
        id: "RP-2026-12",
        ropaId: "RP-2026-12",
        documentName: "ระบบบริหารจัดการเงินเดือนพนักงาน",
        processorName: "บริษัท PayCheck Thailand",
        status: RopaStatus.ReviewPending,
        controllerName: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controllerAddress: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นาย", firstName: "ธนาวุฒิ", lastName: "ศรีสุข",
        address: "99 ถนนรัชดาภิเษก กรุงเทพฯ", email: "thanawut.s@paycheck.co.th",
        phoneNumber: "02-222-3333",
        processingActivity: "การคำนวณและจ่ายเงินเดือนพนักงาน",
        purpose: "เพื่อดำเนินการจ่ายเงินส่ง และนำส่งภาษีตามกฎหมายแรงงาน",
        personalData: "ชื่อ-นามสกุล, เลขประจำตัวประชาชน, เงินเดือน",
        dataCategories: ["employee"],
        dataType: DataType.General, storedDataTypes: ["ชื่อ - นามสกุล", "เลขประจำตัวประชาชน"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Cloud Server"], duration: 10, unit: RetentionUnit.Year, accessCondition: "HR Authorized Only", deletionMethod: "Permanent Delete" },
        legalBasis: "ฐานการปฏิบัติตามสัญญา",
        securityMeasures: { organizational: "HR Access Policy", technical: "Database Encryption" }
    },
    {
        id: "RP-2026-05",
        ropaId: "RP-2026-05",
        documentName: "การจัดเก็บข้อมูลผู้ใช้งานระบบ",
        processorName: "บริษัท Cloud-Solution Ltd.",
        status: RopaStatus.DeletePending,
        controllerName: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controllerAddress: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นาย", firstName: "วิทย์", lastName: "คอมพิวเตอร์",
        address: "เขตพญาไท กรุงเทพฯ", email: "wit.c@cloudsol.th",
        phoneNumber: "02-123-4567",
        processingActivity: "Database Hosting and Management",
        purpose: "เพื่อจัดเก็บข้อมูลโปรไฟล์ผู้ใช้งานของลูกค้า",
        personalData: "Username, Email, Login History",
        dataCategories: ["customer"],
        dataType: DataType.General, storedDataTypes: ["ชื่อ - นามสกุล", "อีเมล"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Cloud DB"], duration: 1, unit: RetentionUnit.Year, accessCondition: "System Admin Only", deletionMethod: "Permanent Delete" },
        legalBasis: "ฐานสัญญา",
        securityMeasures: { technical: "AES-256 Encryption", organizational: "ISO 27001 Certified" }
    },
    {
        id: "RP-2026-06",
        ropaId: "RP-2026-06",
        documentName: "การบริหารจัดการข้อมูลการบริการ",
        processorName: "บริษัท Security-Plus นิติบุคคล",
        status: RopaStatus.DeletePending,
        controllerName: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controllerAddress: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นางสาว", firstName: "อารยา", lastName: "รักษ์ความปลอดภัย",
        address: "จังหวัดนนทบุรี", email: "araya.r@securityplus.co.th",
        phoneNumber: "02-999-8888",
        processingActivity: "Customer Support Log Management",
        purpose: "เพื่อจัดการประวัติการแจ้งปัญหาและการซ่อมบำรุง",
        personalData: "ชื่อลูกค้า, เบอร์ติดต่อ, ปัญหาที่พบ",
        dataCategories: ["customer"],
        dataType: DataType.General, storedDataTypes: ["ชื่อ - นามสกุล", "เบอร์โทรศัพท์"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Secure Archive"], duration: 3, unit: RetentionUnit.Year, accessCondition: "Support Lead Only", deletionMethod: "Shredding/Wiping" },
        legalBasis: "ฐานประโยชน์โดยชอบธรรม",
        securityMeasures: { technical: "Access Logging", organizational: "Privacy Training" }
    },
    {
        id: "RP-2026-07",
        ropaId: "RP-2026-07",
        documentName: "ข้อมูลการสำรวจตลาด",
        processorName: "บริษัท Research Pro",
        status: RopaStatus.DeletePending,
        controllerName: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controllerAddress: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นาย", firstName: "สืบพงศ์", lastName: "วิจัยดี",
        address: "สีลม กรุงเทพฯ", email: "suebpong@researchpro.th",
        phoneNumber: "02-777-1111",
        processingActivity: "Survey Data Analysis",
        purpose: "เพื่อประมวลผลข้อมูลจากการสำรวจตลาด",
        personalData: "ความเห็น, รสนิยม, ข้อมูลเบื้องต้นของผู้ตอบ",
        dataCategories: ["individual"],
        dataType: DataType.General, storedDataTypes: ["เพศ", "ช่วงอายุ"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: true, indirect: false },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Analysis Server"], duration: 1, unit: RetentionUnit.Year, accessCondition: "Analysts Only", deletionMethod: "Data Deletion" },
        legalBasis: "ฐานความยินยอม",
        securityMeasures: { technical: "Pseudonymization" }
    },
    {
        id: "RP-2026-08",
        ropaId: "RP-2026-08",
        documentName: "การจัดการคุกกี้",
        processorName: "บริษัท Web Analytics Co.",
        status: RopaStatus.Processing,
        controllerName: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controllerAddress: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นาย", firstName: "ข้อมูล", lastName: "ดิจิทัล",
        address: "ห้วยขวาง กรุงเทพฯ", email: "info@webanalytics.co.th",
        phoneNumber: "02-555-0000",
        processingActivity: "Website Usage Tracking",
        purpose: "เพื่อวิเคราะห์พฤติกรรมการใช้งานหน้าเว็บไซต์",
        personalData: "IP Address, Client ID",
        dataCategories: ["contact"],
        dataType: DataType.General, storedDataTypes: ["อื่นๆ"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: false, indirect: true },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["Analytics Cloud"], duration: 1, unit: RetentionUnit.Year, accessCondition: "Marketing Admin Only", deletionMethod: "Auto-purge" },
        legalBasis: "ฐานความยินยอม",
        securityMeasures: { technical: "IP Anonymization" }
    },
    {
        id: "RP-2026-09",
        ropaId: "RP-2026-09",
        documentName: "ล็อกระบบเข้าถึงข้อมูล",
        processorName: "บริษัท Cloud Guard Security",
        status: RopaStatus.DeletePending,
        controllerName: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controllerAddress: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นางสาว", firstName: "ปลอดภัย", lastName: "ไว้ก่อน",
        address: "บางนา กรุงเทพฯ", email: "support@cloudguard.th",
        phoneNumber: "02-888-7777",
        processingActivity: "Access Log Storage",
        purpose: "เพื่อจัดเก็บและตรวจสอบประวัติการเข้าใช้งานระบบ",
        personalData: "Login IDs, Timestamps, Activity Logs",
        dataCategories: ["employee"],
        dataType: DataType.General, storedDataTypes: ["อื่นๆ"],
        collectionMethod: CollectionMethod.SoftFile, dataSource: { direct: false, indirect: true },
        internationalTransfer: { isTransfer: false },
        retention: { storageType: CollectionMethod.SoftFile, method: ["WORM Storage"], duration: 10, unit: RetentionUnit.Year, accessCondition: "Security Auditors Only", deletionMethod: "Destructive Overwrite" },
        legalBasis: "ฐานประโยชน์โดยชอบธรรม",
        securityMeasures: { technical: "Audit Trails", organizational: "Incident Response Plan" }
    }
];
