import { OwnerRecord } from "@/types/dataOwner";
import { RopaProcessorRecord } from "@/types/dataProcessor";
import { RopaStatus, DataType, CollectionMethod, RetentionUnit } from "@/types/enums";

/**
 * Standardized DPO Mock Records (RP-2026-01 to RP-2026-13)
 * Optimized for full DPO Audit detail demo.
 */

export const mockOwnerRecords: OwnerRecord[] = [
    {
        id: "RP-2026-01",
        document_name: "บันทึกการเข้าออกคลาวด์เซิร์ฟเวอร์",
        status: RopaStatus.Processing,
        workflow: "processing",
        department: "แผนก IT",
        processor_company: "บริษัท IT Security Pro",
        due_date: "15/03/2569",
        date_created: "01/03/2569",
        updated_date: "14/03/2569",
        processing_status: { do_status: "done", dp_status: "pending" },
        assigned_processor: { name: "นายณัฐวุฒิ ศรีสวัสดิ์", assigned_date: "05/03/2569", processor_status: "ไม่เสร็จสมบูรณ์", document_title: "บันทึกการเข้าออกคลาวด์เซิร์ฟเวอร์" },
        title: "นาย", first_name: "ปิติ", last_name: "สุขสวรรค์",
        address: "อาคารซอฟต์แวร์พาร์ค นนทบุรี",
        email: "piti.s@itsecurity.co.th",
        phone: "02-123-4567",
        data_categories: ["employee", "admin"],
        data_subject_name: "ผู้ดูแลระบบ (Admin)", processing_activity: "System Monitoring",
        purpose_of_processing: "เพื่อรักษาความมั่นคงปลอดภัยทางสารสนเทศ", 
        data_types: [DataType.General], 
        personal_data_items: ["IP Address", "Login Log", "อื่นๆ"], 
        stored_data_types_other: "IP Address, MAC Address",
        collection_method: CollectionMethod.SoftFile, data_source_direct: false, data_source_indirect: true,
        legal_basis: "ฐานประโยชน์โดยชอบธรรม",
        minor_consent_under_10: false, minor_consent_10_to_20: false, minor_consent_none: true,
        has_cross_border_transfer: false,
        retention_value: 90, retention_unit: RetentionUnit.DAYS, access_condition: "IT Admin", deletion_method: "Auto-overwrite",
        exemption_usage: "ไม่มีการใช้หรือเปิดเผยข้อมูลที่ได้รับยกเว้น",
        technical_measures: "IDS/IPS, Log Integrity Check", audit_measures: "SIEM Dashboard",
        risk_assessment: { level: "สูง", probability: 3, impact: 3, total: 9 },
    },
    {
        id: "RP-2026-02",
        document_name: "ข้อมูลธุรกรรมการซื้อขาย",
        status: RopaStatus.Processing,
        workflow: "processing",
        department: "แผนกขาย",
        processor_company: "บริษัท บัญชีดี จำกัด",
        due_date: "18/03/2569",
        date_created: "01/03/2569",
        updated_date: "12/03/2569",
        processing_status: { do_status: "done", dp_status: "done" },
        assigned_processor: { name: "นางสาวพิมพ์ชนก วัฒนากุล", assigned_date: "05/03/2569", processor_status: "เสร็จสมบูรณ์", document_title: "ข้อมูลธุรกรรมการซื้อขาย" },
        title: "นางสาว", first_name: "กัญญา", last_name: "มณีรัตน์",
        address: "123 อาคารพญาไทพลาซ่า กรุงเทพฯ", email: "kanya.m@accounting.co.th",
        phone: "02-987-6543",
        data_categories: ["partner"],
        data_subject_name: "คู่ค้าและซัพพลายเออร์", processing_activity: "Record-to-Report",
        purpose_of_processing: "เพื่อจัดทำบัญชีและเสียภาษีตามกฎหมาย", 
        data_types: [DataType.General], 
        personal_data_items: ["ชื่อบริษัท", "เลขประจำตัวผู้เสียภาษี", "เลขประจำตัวประชาชน", "ชื่อ - นามสกุล"],
        collection_method: CollectionMethod.HardCopy, data_source_direct: true, data_source_indirect: true,
        legal_basis: "ฐานการปฏิบัติตามกฎหมาย",
        minor_consent_under_10: false, minor_consent_10_to_20: false, minor_consent_none: true,
        has_cross_border_transfer: false,
        retention_value: 10, retention_unit: RetentionUnit.YEARS, access_condition: "Finance Manager", deletion_method: "Shredder",
        exemption_usage: "การส่งข้อมูลให้กรมสรรพากร",
        physical_measures: "ห้องเก็บเอกสารล็อคกุญแจ 2 ชั้น", audit_measures: "บันทึกการเข้า-ออกห้องเก็บเอกสาร",
        risk_assessment: { level: "ต่ำ", probability: 1, impact: 2, total: 2 },
    },
    {
        id: "RP-2026-03",
        document_name: "ข้อมูลลูกค้าเพื่อการตลาด",
        status: RopaStatus.Processing,
        workflow: "processing",
        department: "แผนกการตลาด",
        processor_company: "บริษัท NetBay Marketing",
        due_date: "20/03/2569",
        date_created: "01/03/2569",
        updated_date: "10/03/2569",
        processing_status: { do_status: "done", dp_status: "done" },
        assigned_processor: { name: "นายกิตติพงศ์ สุวรรณชัย", assigned_date: "05/03/2569", processor_status: "เสร็จสมบูรณ์", document_title: "ข้อมูลลูกค้าเพื่อการตลาด" },
        title: "นาย", first_name: "ธนากร", last_name: "วัฒนศิริ",
        address: "99/1 ถนนวิภาวดีรังสิต กรุงเทพฯ", email: "thanakorn.w@netbay.co.th",
        phone: "02-555-5555",
        data_categories: ["customer"],
        data_subject_name: "ลูกค้าทั่วไป", processing_activity: "การส่งข่าวสารประชาสัมพันธ์",
        purpose_of_processing: "เพื่อแจ้งสิทธิประโยชน์และกิจกรรมทางการตลาด", 
        data_types: [DataType.General], 
        personal_data_items: ["ชื่อ - นามสกุล", "อีเมล", "เบอร์โทรศัพท์"],
        collection_method: CollectionMethod.SoftFile, data_source_direct: true, data_source_indirect: false,
        legal_basis: "ฐานความยินยอม",
        minor_consent_under_10: false, minor_consent_10_to_20: false, minor_consent_none: true,
        has_cross_border_transfer: false,
        retention_value: 5, retention_unit: RetentionUnit.YEARS, access_condition: "Marketing Team", deletion_method: "ลบไฟล์ถาวร",
        exemption_usage: "ไม่มี",
        technical_measures: "Encryption at rest", access_control_measures: "Role-based Access",
        risk_assessment: { level: "ปานกลาง", probability: 2, impact: 3, total: 6 },
    },
    {
        id: "RP-2026-04",
        document_name: "การดูแลข้อมูลธุรกรรมทางการเงิน",
        status: RopaStatus.ReviewPending,
        workflow: "sent_dpo",
        department: "แผนกบัญชี",
        processor_company: "บริษัท PayCheck Thailand",
        due_date: "01/04/2569",
        date_created: "01/03/2569",
        updated_date: "20/03/2569",
        processing_status: { do_status: "done", dp_status: "done" },
        assigned_processor: { name: "นางสาวศิริพร บุญเหลือ", assigned_date: "02/03/2569", processor_status: "เสร็จสมบูรณ์", document_title: "การดูแลข้อมูลธุรกรรมทางการเงิน" },
        title: "นางสาว", first_name: "รัชนี", last_name: "มีเงิน",
        address: "บางนา กรุงเทพฯ", email: "rajanee@netbay.co.th",
        phone: "02-333-4444",
        data_categories: ["customer", "employee"],
        data_subject_name: "ลูกค้าและพนักงาน", processing_activity: "Financial Transaction Audit",
        purpose_of_processing: "เพื่อตรวจสอบความถูกต้องของธุรกรรมทางการเงิน", 
        data_types: [DataType.General], 
        personal_data_items: ["ชื่อ", "เลขที่บัญชี", "ยอดชำระ", "ชื่อ - นามสกุล", "เลขที่บัญชีธนาคาร"],
        collection_method: CollectionMethod.SoftFile, data_source_direct: true, data_source_indirect: false,
        legal_basis: "ฐานการปฏิบัติตามสัญญา",
        minor_consent_under_10: false, minor_consent_10_to_20: false, minor_consent_none: true,
        has_cross_border_transfer: false,
        retention_value: 7, retention_unit: RetentionUnit.YEARS, access_condition: "Accounting Head", deletion_method: "Database Purge",
        exemption_usage: "รายงานบัญชีต่อหน่วยงานกำกับดูแล",
        technical_measures: "Database Encryption", org_measures: "Access Review Policy",
        risk_assessment: { level: "ต่ำ", probability: 1, impact: 3, total: 3 },
    },
    {
        id: "RP-2026-05",
        document_name: "การจัดเก็บข้อมูลผู้ใช้งานระบบ",
        status: RopaStatus.DeletePending,
        workflow: "delete_pending",
        department: "แผนก IT",
        processor_company: "บริษัท Cloud-Solution Ltd.",
        due_date: "25/03/2569",
        date_created: "01/01/2569",
        updated_date: "15/03/2569",
        processing_status: { do_status: "done", dp_status: "done" },
        assigned_processor: { name: "นายอรรถพล เมืองไทย", assigned_date: "05/01/2569", processor_status: "เสร็จสมบูรณ์", document_title: "การจัดเก็บข้อมูลผู้ใช้งานระบบ" },
        title: "นาย", first_name: "อรรถพล", last_name: "เรืองศรี",
        address: "กรุงเทพฯ", email: "attapol@cloudsol.th",
        phone: "02-111-2222",
        data_categories: ["customer"],
        data_subject_name: "ผู้ใช้งานระบบ CRM", processing_activity: "User Profile Management",
        purpose_of_processing: "เพื่อจัดการข้อมูลสมาชิกและสิทธิการเข้าใช้งาน", 
        data_types: [DataType.General], 
        personal_data_items: ["Username", "Password Hash", "อีเมล", "ชื่อ - นามสกุล"],
        collection_method: CollectionMethod.SoftFile, data_source_direct: true, data_source_indirect: false,
        legal_basis: "ฐานสัญญา",
        minor_consent_under_10: false, minor_consent_10_to_20: false, minor_consent_none: true,
        has_cross_border_transfer: false,
        retention_value: 1, retention_unit: RetentionUnit.YEARS, access_condition: "IT System Owner", deletion_method: "Delete from DB",
        exemption_usage: "ไม่มี",
        technical_measures: "Hash passwords, SSL", access_control_measures: "Token-based Auth",
        risk_assessment: { level: "ปานกลาง", probability: 1, impact: 5, total: 5 },
    },
    {
        id: "RP-2026-06",
        document_name: "การบริหารจัดการข้อมูลการบริการ",
        status: RopaStatus.DeletePending,
        workflow: "delete_pending",
        department: "แผนกบริการลูกค้า",
        processor_company: "บริษัท Security-Plus นิติบุคคล",
        due_date: "10/03/2569",
        date_created: "01/01/2568",
        updated_date: "10/03/2569",
        processing_status: { do_status: "done", dp_status: "done" },
        assigned_processor: { name: "นายสมชาย ใจดี", assigned_date: "02/01/2568", processor_status: "เสร็จสมบูรณ์", document_title: "การบริหารจัดการข้อมูลการบริการ" },
        title: "นาย", first_name: "มานะ", last_name: "อดทน",
        address: "สมุทรปราการ", email: "mana@security.co.th",
        phone: "02-444-5555",
        data_categories: ["customer"],
        data_subject_name: "ลูกค้าที่รับบริการ", processing_activity: "Customer Service Support",
        purpose_of_processing: "เพื่อบันทึกประวัติการรับบริการและแก้ปัญหาการใช้งาน", 
        data_types: [DataType.General], 
        personal_data_items: ["ชื่อ", "เบอร์โทรศัพท์", "ประวัติแจ้งปัญหา", "ชื่อ - นามสกุล"],
        collection_method: CollectionMethod.SoftFile, data_source_direct: true, data_source_indirect: false,
        legal_basis: "ฐานประโยชน์โดยชอบธรรม",
        minor_consent_under_10: false, minor_consent_10_to_20: false, minor_consent_none: true,
        has_cross_border_transfer: false,
        retention_value: 3, retention_unit: RetentionUnit.YEARS, access_condition: "CS Manager", deletion_method: "De-identification",
        exemption_usage: "การพิสูจน์ตัวตนในกรณีพิพาท",
        technical_measures: "Data Masking", org_measures: "Privacy Policy",
        risk_assessment: { level: "ต่ำ", probability: 1, impact: 2, total: 2 },
    },
    {
        id: "RP-2026-07",
        document_name: "ข้อมูลการสำรวจตลาด",
        status: RopaStatus.DeletePending,
        workflow: "delete_pending",
        department: "แผนกวิจัยตลาด",
        due_date: "15/04/2569",
        date_created: "01/01/2569",
        updated_date: "15/01/2569",
        processing_status: { do_status: "done", dp_status: "done" },
        title: "นาย", first_name: "สมคิด", last_name: "มานะชีพ",
        address: "กรุงเทพฯ", email: "somkid@research.co.th",
        phone: "02-999-8888",
        data_categories: ["individual"],
        data_subject_name: "กลุ่มเป้าหมายการสำรวจ", processing_activity: "Market Research Survey",
        purpose_of_processing: "เพื่อวิเคราะห์แนวโน้มตลาดและความต้องการผู้บริโภค", 
        data_types: [DataType.General], 
        personal_data_items: ["เพศ", "อายุ", "ความชอบผลิตภัณฑ์", "ช่วงอายุ"],
        collection_method: CollectionMethod.SoftFile, data_source_direct: true, data_source_indirect: false,
        legal_basis: "ฐานความยินยอม",
        minor_consent_under_10: false, minor_consent_10_to_20: true, minor_consent_none: false,
        has_cross_border_transfer: false,
        retention_value: 1, retention_unit: RetentionUnit.YEARS, access_condition: "Market Research Lead", deletion_method: "Delete from Server",
        exemption_usage: "ไม่มี",
        org_measures: "Retention Policy for Surveys", technical_measures: "Anonymization",
        risk_assessment: { level: "ต่ำ", probability: 1, impact: 1, total: 1 },
    },
    {
        id: "RP-2026-08",
        document_name: "การจัดการคุกกี้",
        status: RopaStatus.Processing,
        workflow: "processing",
        department: "แผนก IT",
        due_date: "20/04/2569",
        date_created: "10/01/2569",
        updated_date: "20/03/2569",
        processing_status: { do_status: "done", dp_status: "done" },
        title: "นาย", first_name: "กิตติ", last_name: "สุขใจ",
        address: "นนทบุรี", email: "kitti@it.com",
        phone: "02-777-6666",
        data_categories: ["contact"],
        data_subject_name: "ผู้เยี่ยมชมเว็บไซต์", processing_activity: "Cookie Tracking",
        purpose_of_processing: "เพื่อวิเคราะห์การใช้งานเว็บไซต์และปรับปรุงประสบการณ์ผู้ใช้", 
        data_types: [DataType.General], 
        personal_data_items: ["Cookie ID", "Browser Settings", "อื่นๆ"], 
        stored_data_types_other: "Cookie ID",
        collection_method: CollectionMethod.SoftFile, data_source_direct: false, data_source_indirect: true,
        legal_basis: "ฐานความยินยอม",
        minor_consent_under_10: false, minor_consent_10_to_20: false, minor_consent_none: true,
        has_cross_border_transfer: false,
        retention_value: 1, retention_unit: RetentionUnit.YEARS, access_condition: "Web Admin", deletion_method: "Auto-clear",
        exemption_usage: "ไม่มี",
        technical_measures: "HTTPS, Cookie Security Flags",
        risk_assessment: { level: "ต่ำ", probability: 1, impact: 1, total: 1 },
    },
    {
        id: "RP-2026-09",
        document_name: "ล็อกระบบเข้าถึงข้อมูล",
        status: RopaStatus.DeletePending,
        workflow: "delete_pending",
        department: "แผนก Security",
        due_date: "15/05/2569",
        date_created: "01/02/2569",
        updated_date: "15/03/2569",
        processing_status: { do_status: "done", dp_status: "done" },
        title: "นาย", first_name: "ยาม", last_name: "เฝ้าหน้าประตู",
        address: "กรุงเทพฯ", email: "guard@secure.co.th",
        phone: "02-121-1212",
        data_categories: ["employee"],
        data_subject_name: "พนักงานที่มีสิทธิ์เข้าถึงข้อมูล", processing_activity: "System Logging",
        purpose_of_processing: "เพื่อรักษาความปลอดภัยและตรวจสอบย้อนหลังการเข้าถึงข้อมูล", 
        data_types: [DataType.General], 
        personal_data_items: ["Log ID", "Access Time", "อื่นๆ"],
        collection_method: CollectionMethod.SoftFile, data_source_direct: false, data_source_indirect: true,
        legal_basis: "ฐานประโยชน์โดยชอบธรรม",
        minor_consent_under_10: false, minor_consent_10_to_20: false, minor_consent_none: true,
        has_cross_border_transfer: false,
        retention_value: 10, retention_unit: RetentionUnit.YEARS, access_condition: "Security Officer", deletion_method: "Overwrite",
        exemption_usage: "ข้อมูลพยานหลักฐานกรณีมีเหตุอาชญากรรม",
        technical_measures: "Admin Log Monitoring", access_control_measures: "Privileged Access Management",
        risk_assessment: { level: "ปานกลาง", probability: 2, impact: 2, total: 4 },
    },
    {
        id: "RP-2026-10",
        document_name: "นโยบายความเป็นส่วนตัว",
        status: RopaStatus.ReviewPending,
        workflow: "sent_dpo",
        department: "แผนกกฎหมาย",
        due_date: "05/04/2569",
        date_created: "01/03/2569",
        updated_date: "20/03/2569",
        processing_status: { do_status: "done", dp_status: "done" },
        title: "นางสาว", first_name: "ยุติธรรม", last_name: "เสมอภาค",
        address: "กรุงเทพฯ", email: "legal@company.co.th",
        phone: "02-131-4151",
        data_categories: ["customer", "partner", "employee"],
        data_subject_name: "ผู้ใช้บริการทั้งหมด", processing_activity: "Privacy Policy Update",
        purpose_of_processing: "เพื่อแจ้งให้เจ้าของข้อมูลทราบถึงรายละเอียดการประมวลผล", 
        data_types: [DataType.General], 
        personal_data_items: ["ไม่มีข้อมูลส่วนบุคคลโดยตรงในนโยบาย", "อื่นๆ"],
        collection_method: CollectionMethod.SoftFile, data_source_direct: true, data_source_indirect: false,
        legal_basis: "ฐานกฎหมาย",
        minor_consent_under_10: false, minor_consent_10_to_20: false, minor_consent_none: true,
        has_cross_border_transfer: false,
        retention_value: 50, retention_unit: RetentionUnit.YEARS, access_condition: "Legal Counsel", deletion_method: "Archive",
        exemption_usage: "ไม่มี",
        org_measures: "Retention Policy Compliance",
        risk_assessment: { level: "ต่ำ", probability: 1, impact: 1, total: 1 },
    },
    {
        id: "RP-2026-11",
        document_name: "ข้อมูลแอปพลิเคชัน",
        status: RopaStatus.Processing,
        workflow: "processing",
        department: "แผนก Digital",
        due_date: "30/05/2569",
        date_created: "01/01/2569",
        updated_date: "01/04/2569",
        processing_status: { do_status: "done", dp_status: "done" },
        title: "นาย", first_name: "ดีิจิทัล", last_name: "แม็กซ์",
        address: "ตึกจตุจักร", email: "max@app.co.th",
        phone: "02-555-9999",
        data_categories: ["customer"],
        data_subject_name: "สมาชิกแอปมือถือ", processing_activity: "Mobile Application Database",
        purpose_of_processing: "เพื่อให้บริการผ่านแอปพลิเคชันมือถือ", 
        data_types: [DataType.General], 
        personal_data_items: ["พิกัด", "ข้อมูลเครื่องมือถือ", "ชื่อ - นามสกุล"],
        collection_method: CollectionMethod.SoftFile, data_source_direct: true, data_source_indirect: false,
        legal_basis: "ฐานสัญญา",
        minor_consent_under_10: false, minor_consent_10_to_20: true, minor_consent_none: false,
        has_cross_border_transfer: false,
        retention_value: 5, retention_unit: RetentionUnit.YEARS, access_condition: "App Developer", deletion_method: "Cloud Purge",
        exemption_usage: "ไม่มี",
        technical_measures: "Encryption, App Scanning", org_measures: "Developer Standards",
        risk_assessment: { level: "สูง", probability: 3, impact: 4, total: 12 },
    },
    {
        id: "RP-2026-12",
        document_name: "ระบบบริหารจัดการเงินเดือนพนักงาน",
        status: RopaStatus.ReviewPending,
        workflow: "sent_dpo",
        department: "แผนก HR",
        processor_company: "บริษัท PayCheck Thailand",
        due_date: "01/04/2569",
        date_created: "01/03/2569",
        updated_date: "20/03/2569",
        processing_status: { do_status: "done", dp_status: "done" },
        assigned_processor: { name: "นางสาวศิริพร บุญเหลือ", assigned_date: "02/03/2569", processor_status: "เสร็จสมบูรณ์", document_title: "ระบบบริหารจัดการเงินเดือนพนักงาน" },
        title: "นางสาว", first_name: "วิภา", last_name: "มหาทรัพย์",
        address: "เขตลาดพร้าว กรุงเทพฯ", email: "wipa@netbay.co.th",
        phone: "02-555-4444",
        data_categories: ["employee"],
        data_subject_name: "พนักงานประจำและสัญญาจ้าง", processing_activity: "Payroll Calculation",
        purpose_of_processing: "เพื่อคำนวณเงินเดือนและนำส่งภาษี/ประกันสังคม", 
        data_types: [DataType.General], 
        personal_data_items: ["ชื่อ", "เลขที่บัญชีธนาคาร", "เงินเดือน", "ชื่อ - นามสกุล", "เลขประจำตัวประชาชน"],
        collection_method: CollectionMethod.SoftFile, data_source_direct: true, data_source_indirect: false,
        legal_basis: "ฐานการปฏิบัติตามกฎหมาย",
        minor_consent_under_10: false, minor_consent_10_to_20: false, minor_consent_none: true,
        has_cross_border_transfer: false,
        retention_value: 10, retention_unit: RetentionUnit.YEARS, access_condition: "HR Manager", deletion_method: "Database Delete",
        exemption_usage: "นำส่งข้อมูลให้สำนักงานประกันสังคม",
        org_measures: "HR Access Policy", technical_measures: "Database Encryption",
        risk_assessment: { level: "ต่ำ", probability: 1, impact: 3, total: 3 },
    },
    {
        id: "RP-2026-13",
        document_name: "ข้อมูลการจ้างงาน",
        status: RopaStatus.Processing,
        workflow: "processing",
        department: "แผนก Recruitment",
        due_date: "15/06/2569",
        date_created: "01/02/2569",
        updated_date: "15/04/2569",
        processing_status: { do_status: "done", dp_status: "done" },
        title: "นาย", first_name: "ว่าจ้าง", last_name: "รุ่งเรือง",
        address: "กรุงเทพฯ", email: "hiring@company.co.th",
        phone: "02-111-2323",
        data_categories: ["candidate"],
        data_subject_name: "ผู้มาสมัครงาน", processing_activity: "Hiring and Interviewing",
        purpose_of_processing: "เพื่อพิจารณาการจ้างงานและคัดเลือกบุคลากรใหม่", 
        data_types: [DataType.General], 
        personal_data_items: ["ประวัติการศึกษา", "CV", "เบอร์ติดต่อ", "ชื่อ - นามสกุล", "วุฒิการศึกษา"],
        collection_method: CollectionMethod.SoftFile, data_source_direct: true, data_source_indirect: false,
        legal_basis: "ฐานความยินยอม",
        minor_consent_under_10: false, minor_consent_10_to_20: false, minor_consent_none: true,
        has_cross_border_transfer: false,
        retention_value: 2, retention_unit: RetentionUnit.YEARS, access_condition: "Recruiter", deletion_method: "Clear files",
        exemption_usage: "ไม่มี",
        org_measures: "Hiring Standards Policy",
        risk_assessment: { level: "ต่ำ", probability: 1, impact: 3, total: 3 },
    },
];

export const mockProcessorRecords: RopaProcessorRecord[] = [
    {
        id: "RP-2026-04",
        document_id: "RP-2026-04",
        processor_name: "บริษัท PayCheck Thailand",
        status: RopaStatus.ReviewPending,
        controller_name: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controller_address: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นาย", first_name: "ธนาวุฒิ", last_name: "ศรีสุข",
        address: "99 ถนนรัชดาภิเษก กรุงเทพฯ", email: "thanawut.s@paycheck.co.th",
        phone: "02-222-3333",
        processor_id: 101,
        updated_at: "2026-03-20T10:00:00Z",
        processing_activity: "การตรวจสอบธุรกรรมทางการเงิน",
        purpose_of_processing: "เพื่อตรวจสอบความถูกต้องของข้อมูลธุรกรรมตามคำสั่ง",
        personal_data_items: [{ id: "1", type: "ชื่อ-นามสกุล" }, { id: "2", type: "เลขประจำตัวประชาชน" }, { id: "3", type: "เงินเดือน" }],
        data_categories: [{ id: "1", category: "customer" }, { id: "2", category: "employee" }],
        data_types: [{ id: "1", type: DataType.General, is_sensitive: false }],
        collection_methods: [{ id: "1", method: CollectionMethod.SoftFile }],
        data_sources: [{ id: "1", source: "direct" }],
        storage_types: [{ id: "1", type: "Cloud Server" }],
        storage_methods: [{ id: "1", method: "Secure Backup" }],
        retention_value: 7, retention_unit: RetentionUnit.YEARS, access_condition: "Contractual Obligation", deletion_method: "Permanent Delete",
        legal_basis: "ฐานสัญญา",
        org_measures: "MFA Authentication", technical_measures: "Database Encryption"
    },
    {
        id: "RP-2026-01",
        document_id: "RP-2026-01",
        processor_name: "บริษัท เน็ตเบย์ เทคโนโลยี จำกัด",
        status: RopaStatus.Approved,
        controller_name: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controller_address: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นาย", first_name: "สิทธิพล", last_name: "ว่องไว",
        address: "456 ถนนสุขุมวิท กรุงเทพฯ", email: "sittipon.v@netbaytech.co.th",
        phone: "02-555-6666",
        processor_id: 102,
        updated_at: "2026-03-14T09:30:00Z",
        processing_activity: "การเชื่อมโยงระบบเครือข่าย",
        purpose_of_processing: "เพื่อให้บริการเชื่อมต่อข้อมูลเสถียร",
        personal_data_items: [{ id: "1", type: "ชื่อ-นามสกุล" }, { id: "2", type: "ที่อยู่ IP" }],
        data_categories: [{ id: "1", category: "customer" }],
        data_types: [{ id: "1", type: DataType.General, is_sensitive: false }],
        collection_methods: [{ id: "1", method: CollectionMethod.SoftFile }],
        data_sources: [{ id: "1", source: "indirect" }],
        storage_types: [{ id: "1", type: "Local Server" }],
        storage_methods: [{ id: "1", method: "Redundant Array" }],
        retention_value: 10, retention_unit: RetentionUnit.YEARS, access_condition: "Admin Only", deletion_method: "Data Scrubbing",
        legal_basis: "ฐานการปฏิบัติตามสัญญา",
        technical_measures: "VPN Access", org_measures: "ISMS Policy"
    },
    {
        id: "RP-2026-02",
        document_id: "RP-2026-02",
        processor_name: "บริษัท ระบบการเงิน จำกัด",
        status: RopaStatus.ReviewPending,
        controller_name: "บริษัท ธนาคารพาณิชย์ จำกัด",
        controller_address: "555 ถนนพหลโยธิน กรุงเทพฯ",
        title: "นางสาว", first_name: "พรทิพย์", last_name: "รักษาดี",
        address: "789 ถนนรัชดาภิเษก กรุงเทพฯ", email: "porntip.r@financesys.co.th",
        phone: "02-987-6543",
        processor_id: 103,
        updated_at: "2026-03-12T15:45:00Z",
        processing_activity: "การบันทึกรายการธุรกรรมประจำวัน",
        purpose_of_processing: "เพื่อตรวจสอบความถูกต้องและป้องกันทุจริต",
        personal_data_items: [{ id: "1", type: "ชื่อ" }, { id: "2", type: "เลขบัญชี" }],
        data_categories: [{ id: "1", category: "customer" }],
        data_types: [{ id: "1", type: DataType.General, is_sensitive: false }],
        collection_methods: [{ id: "1", method: CollectionMethod.SoftFile }],
        data_sources: [{ id: "1", source: "direct" }],
        storage_types: [{ id: "1", type: "Financial Vault" }],
        storage_methods: [{ id: "1", method: "Multiple Keys" }],
        retention_value: 10, retention_unit: RetentionUnit.YEARS, access_condition: "Audit only", deletion_method: "Secure Shredding (Digital)",
        legal_basis: "ฐานกฎหมาย (Financial Laws)",
        technical_measures: "Hardware Security Module (HSM)", org_measures: "Compulsory Audit"
    },
    {
        id: "RP-2026-03",
        document_id: "RP-2026-03",
        processor_name: "บริษัท NetBay Marketing",
        status: RopaStatus.Processing,
        controller_name: "บริษัท เมนคอนโทรลเลอร์ จำกัด",
        controller_address: "99/1 ถนนวิภาวดีรังสิต",
        title: "นาย", first_name: "กิตติพงศ์", last_name: "สุวรรณชัย",
        address: "123 NetBay Company, Bangkok", email: "kittipong@netbay.co.th",
        phone: "02-123-1234",
        processor_id: 104,
        updated_at: "2026-03-10T11:20:00Z",
        processing_activity: "การส่งข่าวสารประชาสัมพันธ์",
        purpose_of_processing: "เพื่อแจ้งสิทธิประโยชน์และโฆษณา",
        personal_data_items: [{ id: "1", type: "ชื่อ - นามสกุล" }, { id: "2", type: "อีเมล" }, { id: "3", type: "เบอร์โทรศัพท์" }],
        data_categories: [{ id: "1", category: "customer" }],
        data_types: [{ id: "1", type: DataType.General, is_sensitive: false }],
        collection_methods: [{ id: "1", method: CollectionMethod.SoftFile }],
        data_sources: [{ id: "1", source: "direct" }],
        storage_types: [{ id: "1", type: "Marketing DB" }],
        storage_methods: [{ id: "1", method: "Encryption" }],
        retention_value: 5, retention_unit: RetentionUnit.YEARS, access_condition: "Consent dependent", deletion_method: "Delete from DB",
        legal_basis: "ฐานความยินยอม",
        technical_measures: "AES-256 Encryption", access_control_measures: "2FA Required"
    },
    {
        id: "RP-2026-12",
        document_id: "RP-2026-12",
        processor_name: "บริษัท PayCheck Thailand",
        status: RopaStatus.ReviewPending,
        controller_name: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controller_address: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นาย", first_name: "ธนาวุฒิ", last_name: "ศรีสุข",
        address: "99 ถนนรัชดาภิเษก กรุงเทพฯ", email: "thanawut.s@paycheck.co.th",
        phone: "02-222-3333",
        processor_id: 101,
        updated_at: "2026-03-20T10:00:00Z",
        processing_activity: "การคำนวณและจ่ายเงินเดือนพนักงาน",
        purpose_of_processing: "เพื่อดำเนินการจ่ายเงินส่ง และนำส่งภาษีตามกฎหมายแรงงาน",
        personal_data_items: [{ id: "1", type: "ชื่อ - นามสกุล" }, { id: "2", type: "เลขประจำตัวประชาชน" }],
        data_categories: [{ id: "1", category: "employee" }],
        data_types: [{ id: "1", type: DataType.General, is_sensitive: false }],
        collection_methods: [{ id: "1", method: CollectionMethod.SoftFile }],
        data_sources: [{ id: "1", source: "direct" }],
        storage_types: [{ id: "1", type: "Payroll System" }],
        storage_methods: [{ id: "1", method: "Access Control" }],
        retention_value: 10, retention_unit: RetentionUnit.YEARS, access_condition: "HR Authorized Only", deletion_method: "Permanent Delete",
        legal_basis: "ฐานการปฏิบัติตามสัญญา",
        org_measures: "HR Access Policy", technical_measures: "Database Encryption"
    },
    {
        id: "RP-2026-05",
        document_id: "RP-2026-05",
        processor_name: "บริษัท Cloud-Solution Ltd.",
        status: RopaStatus.DeletePending,
        controller_name: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controller_address: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นาย", first_name: "วิทย์", last_name: "คอมพิวเตอร์",
        address: "เขตพญาไท กรุงเทพฯ", email: "wit.c@cloudsol.th",
        phone: "02-123-4567",
        processor_id: 105,
        updated_at: "2026-03-15T14:40:00Z",
        processing_activity: "Database Hosting and Management",
        purpose_of_processing: "เพื่อจัดเก็บข้อมูลโปรไฟล์ผู้ใช้งานของลูกค้า",
        personal_data_items: [{ id: "1", type: "Username" }, { id: "2", type: "Email" }, { id: "3", type: "Login History" }],
        data_categories: [{ id: "1", category: "customer" }],
        data_types: [{ id: "1", type: DataType.General, is_sensitive: false }],
        collection_methods: [{ id: "1", method: CollectionMethod.SoftFile }],
        data_sources: [{ id: "1", source: "direct" }],
        storage_types: [{ id: "1", type: "Cloud Infrastructure" }],
        storage_methods: [{ id: "1", method: "Encrypted Volume" }],
        retention_value: 1, retention_unit: RetentionUnit.YEARS, access_condition: "System Admin Only", deletion_method: "Permanent Delete",
        legal_basis: "ฐานสัญญา",
        technical_measures: "AES-256 Encryption", org_measures: "ISO 27001 Certified"
    },
    {
        id: "RP-2026-06",
        document_id: "RP-2026-06",
        processor_name: "บริษัท Security-Plus นิติบุคคล",
        status: RopaStatus.DeletePending,
        controller_name: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controller_address: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นางสาว", first_name: "อารยา", last_name: "รักษ์ความปลอดภัย",
        address: "จังหวัดนนทบุรี", email: "araya.r@securityplus.co.th",
        phone: "02-999-8888",
        processor_id: 106,
        updated_at: "2026-03-10T12:15:00Z",
        processing_activity: "Customer Support Log Management",
        purpose_of_processing: "เพื่อจัดการประวัติการแจ้งปัญหาและการซ่อมบำรุง",
        personal_data_items: [{ id: "1", type: "ชื่อลูกค้า" }, { id: "2", type: "เบอร์ติดต่อ" }, { id: "3", type: "ปัญหาที่พบ" }],
        data_categories: [{ id: "1", category: "customer" }],
        data_types: [{ id: "1", type: DataType.General, is_sensitive: false }],
        collection_methods: [{ id: "1", method: CollectionMethod.SoftFile }],
        data_sources: [{ id: "1", source: "direct" }],
        storage_types: [{ id: "1", type: "Support Portal" }],
        storage_methods: [{ id: "1", method: "Audit Trail" }],
        retention_value: 3, retention_unit: RetentionUnit.YEARS, access_condition: "Support Lead Only", deletion_method: "Shredding/Wiping",
        legal_basis: "ฐานประโยชน์โดยชอบธรรม",
        technical_measures: "Access Logging", org_measures: "Privacy Training"
    },
    {
        id: "RP-2026-07",
        document_id: "RP-2026-07",
        processor_name: "บริษัท Research Pro",
        status: RopaStatus.DeletePending,
        controller_name: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controller_address: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นาย", first_name: "สืบพงศ์", last_name: "วิจัยดี",
        address: "สีลม กรุงเทพฯ", email: "suebpong@researchpro.th",
        phone: "02-777-1111",
        processor_id: 107,
        updated_at: "2026-01-15T16:00:00Z",
        processing_activity: "Survey Data Analysis",
        purpose_of_processing: "เพื่อประมวลผลข้อมูลจากการสำรวจตลาด",
        personal_data_items: [{ id: "1", type: "ความเห็น" }, { id: "2", type: "รสนิยม" }, { id: "3", type: "ข้อมูลเบื้องต้นของผู้ตอบ" }],
        data_categories: [{ id: "1", category: "individual" }],
        data_types: [{ id: "1", type: DataType.General, is_sensitive: false }],
        collection_methods: [{ id: "1", method: CollectionMethod.SoftFile }],
        data_sources: [{ id: "1", source: "direct" }],
        storage_types: [{ id: "1", type: "Analysis Tool" }],
        storage_methods: [{ id: "1", method: "Pseudonymization" }],
        retention_value: 1, retention_unit: RetentionUnit.YEARS, access_condition: "Analysts Only", deletion_method: "Data Deletion",
        legal_basis: "ฐานความยินยอม",
        technical_measures: "Pseudonymization"
    },
    {
        id: "RP-2026-08",
        document_id: "RP-2026-08",
        processor_name: "บริษัท Web Analytics Co.",
        status: RopaStatus.Processing,
        controller_name: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controller_address: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นาย", first_name: "ข้อมูล", last_name: "ดิจิทัล",
        address: "ห้วยขวาง กรุงเทพฯ", email: "info@webanalytics.co.th",
        phone: "02-555-0000",
        processor_id: 108,
        updated_at: "2026-03-20T17:30:00Z",
        processing_activity: "Website Usage Tracking",
        purpose_of_processing: "เพื่อวิเคราะห์พฤติกรรมการใช้งานหน้าเว็บไซต์",
        personal_data_items: [{ id: "1", type: "IP Address" }, { id: "2", type: "Client ID" }],
        data_categories: [{ id: "1", category: "contact" }],
        data_types: [{ id: "1", type: DataType.General, is_sensitive: false }],
        collection_methods: [{ id: "1", method: CollectionMethod.SoftFile }],
        data_sources: [{ id: "1", source: "indirect" }],
        storage_types: [{ id: "1", type: "Analytics Engine" }],
        storage_methods: [{ id: "1", method: "Anonymization" }],
        retention_value: 1, retention_unit: RetentionUnit.YEARS, access_condition: "Marketing Admin Only", deletion_method: "Auto-purge",
        legal_basis: "ฐานความยินยอม",
        technical_measures: "IP Anonymization"
    },
    {
        id: "RP-2026-09",
        document_id: "RP-2026-09",
        processor_name: "บริษัท Cloud Guard Security",
        status: RopaStatus.DeletePending,
        controller_name: "บริษัท เน็ตเบย์ จำกัด (มหาชน)",
        controller_address: "123 อาคารเน็ตเบย์ กรุงเทพฯ",
        title: "นางสาว", first_name: "ปลอดภัย", last_name: "ไว้ก่อน",
        address: "บางนา กรุงเทพฯ", email: "support@cloudguard.th",
        phone: "02-888-7777",
        processor_id: 109,
        updated_at: "2026-03-15T08:00:00Z",
        processing_activity: "Access Log Storage",
        purpose_of_processing: "เพื่อจัดเก็บและตรวจสอบประวัติการเข้าใช้งานระบบ",
        personal_data_items: [{ id: "1", type: "Login IDs" }, { id: "2", type: "Timestamps" }, { id: "3", type: "Activity Logs" }],
        data_categories: [{ id: "1", category: "employee" }],
        data_types: [{ id: "1", type: DataType.General, is_sensitive: false }],
        collection_methods: [{ id: "1", method: CollectionMethod.SoftFile }],
        data_sources: [{ id: "1", source: "indirect" }],
        storage_types: [{ id: "1", type: "Security SIEM" }],
        storage_methods: [{ id: "1", method: "Hash Chaining" }],
        retention_value: 10, retention_unit: RetentionUnit.YEARS, access_condition: "Security Auditors Only", deletion_method: "Destructive Overwrite",
        legal_basis: "ฐานประโยชน์โดยชอบธรรม",
        technical_measures: "Audit Trails", org_measures: "Incident Response Plan"
    }
];
